# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/company.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16protobuf/company.proto\x12\x07\x63ompany\"\x99\x02\n\x0c\x43ompanyProto\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08logo_url\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\x0f\n\x07website\x18\x05 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x06 \x01(\t\x12\r\n\x05phone\x18\x07 \x01(\t\x12\r\n\x05\x65mail\x18\x08 \x01(\t\x12\x14\n\x0c\x63ompany_type\x18\t \x01(\t\x12\x0c\n\x04size\x18\n \x01(\t\x12\x10\n\x08industry\x18\x0b \x01(\t\x12\x11\n\tis_active\x18\x0c \x01(\x08\x12\x17\n\x0fmember_user_ids\x18\r \x03(\t\x12\x12\n\ncreated_at\x18\x0e \x01(\t\x12\x12\n\nupdated_at\x18\x0f \x01(\t\"\xa6\x01\n\x16\x43ompanyMembershipProto\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\ncompany_id\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\t\x12\x0c\n\x04role\x18\x04 \x01(\t\x12\x12\n\ndepartment\x18\x05 \x01(\t\x12\x10\n\x08position\x18\x06 \x01(\t\x12\x13\n\x0b\x64\x61te_joined\x18\x07 \x01(\t\x12\x12\n\nis_primary\x18\x08 \x01(\x08\"\xb4\x01\n\x14\x43ompanyDocumentProto\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\ncompany_id\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\x10\n\x08\x66ile_url\x18\x05 \x01(\t\x12\x15\n\rdocument_type\x18\x06 \x01(\t\x12\x1b\n\x13uploaded_by_user_id\x18\x07 \x01(\t\x12\x13\n\x0buploaded_at\x18\x08 \x01(\t\"=\n\x11\x43ompanyCollection\x12(\n\tcompanies\x18\x01 \x03(\x0b\x32\x15.company.CompanyProto\"S\n\x1b\x43ompanyMembershipCollection\x12\x34\n\x0bmemberships\x18\x01 \x03(\x0b\x32\x1f.company.CompanyMembershipProto\"M\n\x19\x43ompanyDocumentCollection\x12\x30\n\tdocuments\x18\x01 \x03(\x0b\x32\x1d.company.CompanyDocumentProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protobuf.company_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_COMPANYPROTO']._serialized_start=36
  _globals['_COMPANYPROTO']._serialized_end=317
  _globals['_COMPANYMEMBERSHIPPROTO']._serialized_start=320
  _globals['_COMPANYMEMBERSHIPPROTO']._serialized_end=486
  _globals['_COMPANYDOCUMENTPROTO']._serialized_start=489
  _globals['_COMPANYDOCUMENTPROTO']._serialized_end=669
  _globals['_COMPANYCOLLECTION']._serialized_start=671
  _globals['_COMPANYCOLLECTION']._serialized_end=732
  _globals['_COMPANYMEMBERSHIPCOLLECTION']._serialized_start=734
  _globals['_COMPANYMEMBERSHIPCOLLECTION']._serialized_end=817
  _globals['_COMPANYDOCUMENTCOLLECTION']._serialized_start=819
  _globals['_COMPANYDOCUMENTCOLLECTION']._serialized_end=896
# @@protoc_insertion_point(module_scope)
