# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/landing.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16protobuf/landing.proto\x12\x07landing\"(\n\x17NewsletterSignupRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\"<\n\x18NewsletterSignupResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"-\n\x07\x46\x65\x61ture\x12\r\n\x05title\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\"#\n\x04Stat\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05\",\n\x0bTestimonial\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"\xe8\x01\n\x12LandingPageContent\x12\x12\n\nhero_title\x18\x01 \x01(\t\x12\x15\n\rhero_subtitle\x18\x02 \x01(\t\x12\"\n\x08\x66\x65\x61tures\x18\x03 \x03(\x0b\x32\x10.landing.Feature\x12\x1c\n\x05stats\x18\x04 \x03(\x0b\x32\r.landing.Stat\x12\x10\n\x08\x62\x65nefits\x18\x05 \x03(\t\x12*\n\x0ctestimonials\x18\x06 \x03(\x0b\x32\x14.landing.Testimonial\x12\x11\n\tcta_title\x18\x07 \x01(\t\x12\x14\n\x0c\x63ta_subtitle\x18\x08 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protobuf.landing_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_NEWSLETTERSIGNUPREQUEST']._serialized_start=35
  _globals['_NEWSLETTERSIGNUPREQUEST']._serialized_end=75
  _globals['_NEWSLETTERSIGNUPRESPONSE']._serialized_start=77
  _globals['_NEWSLETTERSIGNUPRESPONSE']._serialized_end=137
  _globals['_FEATURE']._serialized_start=139
  _globals['_FEATURE']._serialized_end=184
  _globals['_STAT']._serialized_start=186
  _globals['_STAT']._serialized_end=221
  _globals['_TESTIMONIAL']._serialized_start=223
  _globals['_TESTIMONIAL']._serialized_end=267
  _globals['_LANDINGPAGECONTENT']._serialized_start=270
  _globals['_LANDINGPAGECONTENT']._serialized_end=502
# @@protoc_insertion_point(module_scope)
