from _typeshed import Incomplete
from core.constants import STATUS_NOT_STARTED

OBLIGATION_DEFAULT_STATUS = STATUS_NOT_STARTED
FREQUENCY_DAILY: str
FREQUENCY_WEEKLY: str
FREQUENCY_FORTNIGHTLY: str
FREQUENCY_MONTHLY: str
FREQUENCY_QUARTERLY: str
FREQUENCY_BIANNUAL: str
FREQUENCY_ANNUAL: str
FREQUENCY_ALIASES: Incomplete
