from _typeshed import Incomplete
from django.core.management.base import BaseCommand
from subprocess import CompletedProcess

logger: Incomplete

class Command(BaseCommand):
    help: str
    def add_arguments(self, parser) -> None: ...
    def handle(self, *args, **options) -> None: ...
    def process_app(self, app_config, force: bool = False) -> None: ...
    def _get_protoc_path(self): ...
    def _get_proto_files(self, proto_dir): ...
    def _process_proto_files(self, proto_files, paths, force: bool = False) -> None: ...
    def _compile_proto_file(self, proto_file, paths, force) -> None: ...
    def _validate_paths(self, paths, proto_path) -> None: ...
    def _run_protoc_command(self, paths): ...
    def _secure_command_exec(self, cmd, timeout: int = 30) -> CompletedProcess: ...
    def _verify_generated_file(self, proto_file, output_dir): ...
    def _handle_compilation_error(self, proto_file, error) -> None: ...
    def _show_installation_instructions(self) -> None: ...
