from .forms import CompanyForm
from .mixins import CompanyAccessMixin
from .models import Company
from _typeshed import Incomplete
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpRequest, HttpResponse
from django.views.generic import CreateView, DeleteView, ListView, UpdateView

logger: Incomplete
User: Incomplete

def is_company_admin(user: User) -> bool: ...

class CompanyListView(LoginRequiredMixin, CompanyAccessMixin, ListView):
    model = Company
    template_name: str
    context_object_name: str
    paginate_by: int
    def get_queryset(self): ...
    def get_context_data(self, **kwargs): ...
    object_list: Incomplete
    def get(self, request, *args, **kwargs): ...

class CompanyCreateView(LoginRequiredMixin, CreateView):
    model = Company
    form_class = CompanyForm
    template_name: str
    success_url: Incomplete
    def dispatch(self, request, *args, **kwargs): ...
    def get_context_data(self, **kwargs): ...
    def form_valid(self, form): ...
    def form_invalid(self, form): ...

class CompanyUpdateView(LoginRequiredMixin, CompanyAccessMixin, UpdateView):
    model = Company
    form_class = CompanyForm
    template_name: str
    context_object_name: str
    pk_url_kwarg: str
    def get_success_url(self): ...
    def get_context_data(self, **kwargs): ...
    def form_valid(self, form): ...
    def form_invalid(self, form): ...

class CompanyDeleteView(LoginRequiredMixin, CompanyAccessMixin, DeleteView):
    model = Company
    template_name: str
    context_object_name: str
    success_url: Incomplete
    pk_url_kwarg: str
    def dispatch(self, request, *args, **kwargs): ...
    def delete(self, request, *args, **kwargs): ...

@login_required
def company_detail(request: HttpRequest, company_id: int) -> HttpResponse: ...
@login_required
def manage_members(request: HttpRequest, company_id: int) -> HttpResponse: ...
@login_required
def add_member(request: HttpRequest, company_id: int) -> HttpResponse: ...
@login_required
def remove_member(request: HttpRequest, company_id: int, member_id: int) -> HttpResponse: ...
@login_required
def update_member_role(request: HttpRequest, company_id: int, member_id: int) -> HttpResponse: ...
@login_required
def upload_document(request: HttpRequest, company_id: int) -> HttpResponse: ...
@login_required
def delete_document(request: HttpRequest, company_id: int, document_id: int) -> HttpResponse: ...
