from _typeshed import Incomplete
from datetime import date, datetime

register: Incomplete

@register.filter
def format_due_date(target_date: datetime | date | None) -> str: ...
@register.filter
def multiply(value, arg): ...
@register.simple_tag
def status_badge(status: str) -> str: ...
@register.filter
def display_status(obligation): ...
@register.filter
def display_responsibility(responsibility): ...
