from _typeshed import Incomplete
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.http import HttpRequest, HttpResponse
from django.views.generic import ListView

User: Incomplete

def is_admin(user: User) -> bool: ...

class UserListView(LoginRequiredMixin, UserPassesTestMixin, ListView):
    model = User
    template_name: str
    context_object_name: str
    def test_func(self): ...
    def get_queryset(self): ...

@login_required
def profile_view(request: HttpRequest) -> HttpResponse: ...
@login_required
def profile_edit(request: HttpRequest) -> HttpResponse: ...
@login_required
def change_password(request): ...
@login_required
def upload_profile_image(request): ...
def admin_user_list(request): ...
def admin_user_create(request): ...
def admin_user_edit(request, user_id): ...
def admin_user_delete(request, user_id): ...
