from typing import Any

class HTMXMiddleware:
    def __init__(self, get_response: Any) -> None: ...
    def __call__(self, request: Any) -> Any: ...

# HTMX details class for request.htmx
class HTMXDetails:
    def __init__(self, request: Any) -> None: ...
    @property
    def boosted(self) -> bool: ...
    @property
    def current_url(self) -> str | None: ...
    @property
    def history_restore_request(self) -> bool: ...
    @property
    def prompt(self) -> str | None: ...
    @property
    def request(self) -> str | None: ...
    @property
    def target(self) -> str | None: ...
    @property
    def trigger(self) -> str | None: ...
    @property
    def trigger_name(self) -> str | None: ...

# Add HtmxHttpRequest for type checking
class HtmxHttpRequest:
    htmx: HTMXDetails
