from collections.abc import Callable
from typing import Any

def django_htmx_script() -> str: ...
def hx_get() -> Callable[..., str]: ...
def hx_post() -> Callable[..., str]: ...
def hx_put() -> Callable[..., str]: ...
def hx_delete() -> Callable[..., str]: ...
def hx_patch() -> Callable[..., str]: ...
def hx_boost() -> Callable[..., str]: ...
def hx_push_url() -> Callable[..., str]: ...
def hx_target() -> Callable[..., str]: ...
def hx_swap() -> Callable[..., str]: ...
def hx_trigger() -> Callable[..., str]: ...
def htmx_extension() -> dict[str, Any]: ...
