from .models import Project
from _typeshed import Incomplete
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import AbstractUser
from django.http import HttpRequest, HttpResponse, JsonResponse
from django.views.generic import ListView, TemplateView
from typing import Any, TypeVar

User: Incomplete
logger: Incomplete
T = TypeVar('T')

class ProjectSelectionView(LoginRequiredMixin, TemplateView):
    template_name: str
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]: ...
    def get(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse: ...
    def requires_special_access(self, project_id: str, _user: AbstractUser) -> bool: ...

class ProjectListView(LoginRequiredMixin, ListView):
    model = Project
    template_name: str
    context_object_name: str
    def get_queryset(self): ...

def project_obligations(_request: HttpRequest, project_id: str) -> JsonResponse: ...
def get_user_role(project: Project, user: AbstractUser) -> str: ...
def get_item(dictionary: dict, key: Any) -> Any: ...
def apply_to_all(queryset: Any, method_name: str) -> list: ...
def format_role(role: str) -> str: ...
def role_badge(role: str) -> dict: ...
def obligation_table(obligations_list: list) -> dict: ...
def get_project(project_id: str) -> Project: ...
def get_user(user_id: str) -> AbstractUser: ...
def get_role_display(role_value: str) -> str: ...
def get_role_color(role_value: str) -> str: ...
def get_role_choices() -> list[tuple[str, str]]: ...
def get_responsibility_choices() -> list[tuple[str, str]]: ...
def get_role_from_responsibility(responsibility: str) -> str: ...
def get_responsibility_from_role(role: str) -> str: ...
def get_responsibility_display_name(responsibility: str) -> str: ...
