# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for more information:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
# https://containers.dev/guide/dependabot

version: 2
updates:
  # Enable version updates for devcontainers
<<<<<<< HEAD
  - package-ecosystem: 'devcontainer'
    directory: '/'
=======
  - package-ecosystem: "devcontainer"
    directory: "/"
>>>>>>> b3f8326 (release(v0.0.4): comprehensive platform enhancements and new features (#6))
    schedule:
      interval: weekly

  # Enable version updates for npm
<<<<<<< HEAD
  - package-ecosystem: 'npm'
    directory: '/'
=======
  - package-ecosystem: "npm"
    directory: "/"
>>>>>>> b3f8326 (release(v0.0.4): comprehensive platform enhancements and new features (#6))
    schedule:
      interval: quarterly

  # Enable version updates for python
<<<<<<< HEAD
  - package-ecosystem: 'python'
    directory: '/'
=======
  - package-ecosystem: "python"
    directory: "/"
>>>>>>> b3f8326 (release(v0.0.4): comprehensive platform enhancements and new features (#6))
    schedule:
      interval: quarterly
