# Dependabot configuration for automated dependency updates
# For more information, see:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Enable version updates for devcontainers
  - package-ecosystem: 'devcontainers' # Updates for devcontainer features
    directory: '/' # Root directory of the repository
    schedule:
      interval: weekly # Check for updates every week

  # Enable version updates for npm dependencies
  - package-ecosystem: 'npm' # Updates for Node.js dependencies
    directory: '/' # Root directory of the repository
    schedule:
      interval: monthly # Check for updates every month

  # Enable version updates for Python dependencies
  - package-ecosystem: 'pip' # Updates for Python dependencies
    directory: '/' # Root directory of the repository
    schedule:
      interval: monthly # Check for updates every month
