[mypy]
python_version = 3.12
strict = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
warn_unused_ignores = true
warn_return_any = true
warn_unused_configs = true
show_error_codes = true
ignore_missing_imports = false
namespace_packages = true
exclude = 'migrations|venv|\.venv|tests/|test_|__init__\.py|.*_pb2\.py$'

[mypy-django_tables2*]
ignore_missing_imports = True

[mypy-django_tables2.views*]
ignore_missing_imports = True
