// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.24.4

import { Writer, Reader } from "as-proto/assembly";
import { ObligationProto } from "./ObligationProto";

export class ObligationCollection {
  static encode(message: ObligationCollection, writer: Writer): void {
    const obligations = message.obligations;
    for (let i: i32 = 0; i < obligations.length; ++i) {
      writer.uint32(10);
      writer.fork();
      ObligationProto.encode(obligations[i], writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): ObligationCollection {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new ObligationCollection();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.obligations.push(
            ObligationProto.decode(reader, reader.uint32())
          );
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  obligations: Array<ObligationProto>;

  constructor(obligations: Array<ObligationProto> = []) {
    this.obligations = obligations;
  }
}
