// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.24.4

import { Writer, Reader } from "as-proto/assembly";

export class ObligationProto {
  static encode(message: ObligationProto, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.obligationNumber);

    writer.uint32(18);
    writer.string(message.projectId);

    writer.uint32(26);
    writer.string(message.primaryEnvironmentalMechanismId);

    writer.uint32(34);
    writer.string(message.procedure);

    writer.uint32(42);
    writer.string(message.environmentalAspect);

    writer.uint32(50);
    writer.string(message.customEnvironmentalAspect);

    writer.uint32(58);
    writer.string(message.obligation);

    writer.uint32(66);
    writer.string(message.accountability);

    const responsibleUserIds = message.responsibleUserIds;
    if (responsibleUserIds.length !== 0) {
      for (let i: i32 = 0; i < responsibleUserIds.length; ++i) {
        writer.uint32(74);
        writer.string(responsibleUserIds[i]);
      }
    }

    writer.uint32(82);
    writer.string(message.projectPhase);

    writer.uint32(90);
    writer.string(message.actionDueDate);

    writer.uint32(98);
    writer.string(message.closeOutDate);

    writer.uint32(106);
    writer.string(message.status);

    writer.uint32(114);
    writer.string(message.supportingInformation);

    writer.uint32(122);
    writer.string(message.generalComments);

    writer.uint32(130);
    writer.string(message.evidenceNotes);

    writer.uint32(136);
    writer.bool(message.recurringObligation);

    writer.uint32(146);
    writer.string(message.recurringFrequency);

    writer.uint32(154);
    writer.string(message.recurringStatus);

    writer.uint32(162);
    writer.string(message.recurringForecastedDate);

    writer.uint32(168);
    writer.bool(message.inspection);

    writer.uint32(178);
    writer.string(message.inspectionFrequency);

    writer.uint32(186);
    writer.string(message.siteOrDesktop);

    writer.uint32(192);
    writer.bool(message.newControlActionRequired);

    writer.uint32(202);
    writer.string(message.obligationType);

    writer.uint32(208);
    writer.bool(message.gapAnalysis);

    writer.uint32(218);
    writer.string(message.notesForGapAnalysis);

    writer.uint32(226);
    writer.string(message.createdAt);

    writer.uint32(234);
    writer.string(message.updatedAt);
  }

  static decode(reader: Reader, length: i32): ObligationProto {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new ObligationProto();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.obligationNumber = reader.string();
          break;

        case 2:
          message.projectId = reader.string();
          break;

        case 3:
          message.primaryEnvironmentalMechanismId = reader.string();
          break;

        case 4:
          message.procedure = reader.string();
          break;

        case 5:
          message.environmentalAspect = reader.string();
          break;

        case 6:
          message.customEnvironmentalAspect = reader.string();
          break;

        case 7:
          message.obligation = reader.string();
          break;

        case 8:
          message.accountability = reader.string();
          break;

        case 9:
          message.responsibleUserIds.push(reader.string());
          break;

        case 10:
          message.projectPhase = reader.string();
          break;

        case 11:
          message.actionDueDate = reader.string();
          break;

        case 12:
          message.closeOutDate = reader.string();
          break;

        case 13:
          message.status = reader.string();
          break;

        case 14:
          message.supportingInformation = reader.string();
          break;

        case 15:
          message.generalComments = reader.string();
          break;

        case 16:
          message.evidenceNotes = reader.string();
          break;

        case 17:
          message.recurringObligation = reader.bool();
          break;

        case 18:
          message.recurringFrequency = reader.string();
          break;

        case 19:
          message.recurringStatus = reader.string();
          break;

        case 20:
          message.recurringForecastedDate = reader.string();
          break;

        case 21:
          message.inspection = reader.bool();
          break;

        case 22:
          message.inspectionFrequency = reader.string();
          break;

        case 23:
          message.siteOrDesktop = reader.string();
          break;

        case 24:
          message.newControlActionRequired = reader.bool();
          break;

        case 25:
          message.obligationType = reader.string();
          break;

        case 26:
          message.gapAnalysis = reader.bool();
          break;

        case 27:
          message.notesForGapAnalysis = reader.string();
          break;

        case 28:
          message.createdAt = reader.string();
          break;

        case 29:
          message.updatedAt = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  obligationNumber: string;
  projectId: string;
  primaryEnvironmentalMechanismId: string;
  procedure: string;
  environmentalAspect: string;
  customEnvironmentalAspect: string;
  obligation: string;
  accountability: string;
  responsibleUserIds: Array<string>;
  projectPhase: string;
  actionDueDate: string;
  closeOutDate: string;
  status: string;
  supportingInformation: string;
  generalComments: string;
  evidenceNotes: string;
  recurringObligation: bool;
  recurringFrequency: string;
  recurringStatus: string;
  recurringForecastedDate: string;
  inspection: bool;
  inspectionFrequency: string;
  siteOrDesktop: string;
  newControlActionRequired: bool;
  obligationType: string;
  gapAnalysis: bool;
  notesForGapAnalysis: string;
  createdAt: string;
  updatedAt: string;

  constructor(
    obligationNumber: string = "",
    projectId: string = "",
    primaryEnvironmentalMechanismId: string = "",
    procedure: string = "",
    environmentalAspect: string = "",
    customEnvironmentalAspect: string = "",
    obligation: string = "",
    accountability: string = "",
    responsibleUserIds: Array<string> = [],
    projectPhase: string = "",
    actionDueDate: string = "",
    closeOutDate: string = "",
    status: string = "",
    supportingInformation: string = "",
    generalComments: string = "",
    evidenceNotes: string = "",
    recurringObligation: bool = false,
    recurringFrequency: string = "",
    recurringStatus: string = "",
    recurringForecastedDate: string = "",
    inspection: bool = false,
    inspectionFrequency: string = "",
    siteOrDesktop: string = "",
    newControlActionRequired: bool = false,
    obligationType: string = "",
    gapAnalysis: bool = false,
    notesForGapAnalysis: string = "",
    createdAt: string = "",
    updatedAt: string = ""
  ) {
    this.obligationNumber = obligationNumber;
    this.projectId = projectId;
    this.primaryEnvironmentalMechanismId = primaryEnvironmentalMechanismId;
    this.procedure = procedure;
    this.environmentalAspect = environmentalAspect;
    this.customEnvironmentalAspect = customEnvironmentalAspect;
    this.obligation = obligation;
    this.accountability = accountability;
    this.responsibleUserIds = responsibleUserIds;
    this.projectPhase = projectPhase;
    this.actionDueDate = actionDueDate;
    this.closeOutDate = closeOutDate;
    this.status = status;
    this.supportingInformation = supportingInformation;
    this.generalComments = generalComments;
    this.evidenceNotes = evidenceNotes;
    this.recurringObligation = recurringObligation;
    this.recurringFrequency = recurringFrequency;
    this.recurringStatus = recurringStatus;
    this.recurringForecastedDate = recurringForecastedDate;
    this.inspection = inspection;
    this.inspectionFrequency = inspectionFrequency;
    this.siteOrDesktop = siteOrDesktop;
    this.newControlActionRequired = newControlActionRequired;
    this.obligationType = obligationType;
    this.gapAnalysis = gapAnalysis;
    this.notesForGapAnalysis = notesForGapAnalysis;
    this.createdAt = createdAt;
    this.updatedAt = updatedAt;
  }
}
