from _typeshed import Incomplete
from typing import Any

register: Incomplete

@register.filter
def format_procedure_name(name: str) -> str: ...
@register.filter
def format_procedure_status(status: str) -> str: ...
@register.simple_tag
def procedure_status_badge(status: str) -> str: ...
def procedure_stats(stats: dict[str, int]) -> dict[str, Any]: ...
def procedure_chart_card(procedure: dict[str, Any]) -> dict[str, Any]: ...
