// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.24.4

import { Writer, Reader } from "as-proto/assembly";

export class CompanyProto {
  static encode(message: CompanyProto, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.id);

    writer.uint32(18);
    writer.string(message.name);

    writer.uint32(26);
    writer.string(message.logoUrl);

    writer.uint32(34);
    writer.string(message.description);

    writer.uint32(42);
    writer.string(message.website);

    writer.uint32(50);
    writer.string(message.address);

    writer.uint32(58);
    writer.string(message.phone);

    writer.uint32(66);
    writer.string(message.email);

    writer.uint32(74);
    writer.string(message.companyType);

    writer.uint32(82);
    writer.string(message.size);

    writer.uint32(90);
    writer.string(message.industry);

    writer.uint32(96);
    writer.bool(message.isActive);

    const memberUserIds = message.memberUserIds;
    if (memberUserIds.length !== 0) {
      for (let i: i32 = 0; i < memberUserIds.length; ++i) {
        writer.uint32(106);
        writer.string(memberUserIds[i]);
      }
    }

    writer.uint32(114);
    writer.string(message.createdAt);

    writer.uint32(122);
    writer.string(message.updatedAt);
  }

  static decode(reader: Reader, length: i32): CompanyProto {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new CompanyProto();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.id = reader.string();
          break;

        case 2:
          message.name = reader.string();
          break;

        case 3:
          message.logoUrl = reader.string();
          break;

        case 4:
          message.description = reader.string();
          break;

        case 5:
          message.website = reader.string();
          break;

        case 6:
          message.address = reader.string();
          break;

        case 7:
          message.phone = reader.string();
          break;

        case 8:
          message.email = reader.string();
          break;

        case 9:
          message.companyType = reader.string();
          break;

        case 10:
          message.size = reader.string();
          break;

        case 11:
          message.industry = reader.string();
          break;

        case 12:
          message.isActive = reader.bool();
          break;

        case 13:
          message.memberUserIds.push(reader.string());
          break;

        case 14:
          message.createdAt = reader.string();
          break;

        case 15:
          message.updatedAt = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  id: string;
  name: string;
  logoUrl: string;
  description: string;
  website: string;
  address: string;
  phone: string;
  email: string;
  companyType: string;
  size: string;
  industry: string;
  isActive: bool;
  memberUserIds: Array<string>;
  createdAt: string;
  updatedAt: string;

  constructor(
    id: string = "",
    name: string = "",
    logoUrl: string = "",
    description: string = "",
    website: string = "",
    address: string = "",
    phone: string = "",
    email: string = "",
    companyType: string = "",
    size: string = "",
    industry: string = "",
    isActive: bool = false,
    memberUserIds: Array<string> = [],
    createdAt: string = "",
    updatedAt: string = ""
  ) {
    this.id = id;
    this.name = name;
    this.logoUrl = logoUrl;
    this.description = description;
    this.website = website;
    this.address = address;
    this.phone = phone;
    this.email = email;
    this.companyType = companyType;
    this.size = size;
    this.industry = industry;
    this.isActive = isActive;
    this.memberUserIds = memberUserIds;
    this.createdAt = createdAt;
    this.updatedAt = updatedAt;
  }
}
