// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.24.4

import { Writer, Reader } from "as-proto/assembly";

export class CompanyDocumentProto {
  static encode(message: CompanyDocumentProto, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.id);

    writer.uint32(18);
    writer.string(message.companyId);

    writer.uint32(26);
    writer.string(message.name);

    writer.uint32(34);
    writer.string(message.description);

    writer.uint32(42);
    writer.string(message.fileUrl);

    writer.uint32(50);
    writer.string(message.documentType);

    writer.uint32(58);
    writer.string(message.uploadedByUserId);

    writer.uint32(66);
    writer.string(message.uploadedAt);
  }

  static decode(reader: Reader, length: i32): CompanyDocumentProto {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new CompanyDocumentProto();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.id = reader.string();
          break;

        case 2:
          message.companyId = reader.string();
          break;

        case 3:
          message.name = reader.string();
          break;

        case 4:
          message.description = reader.string();
          break;

        case 5:
          message.fileUrl = reader.string();
          break;

        case 6:
          message.documentType = reader.string();
          break;

        case 7:
          message.uploadedByUserId = reader.string();
          break;

        case 8:
          message.uploadedAt = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  id: string;
  companyId: string;
  name: string;
  description: string;
  fileUrl: string;
  documentType: string;
  uploadedByUserId: string;
  uploadedAt: string;

  constructor(
    id: string = "",
    companyId: string = "",
    name: string = "",
    description: string = "",
    fileUrl: string = "",
    documentType: string = "",
    uploadedByUserId: string = "",
    uploadedAt: string = ""
  ) {
    this.id = id;
    this.companyId = companyId;
    this.name = name;
    this.description = description;
    this.fileUrl = fileUrl;
    this.documentType = documentType;
    this.uploadedByUserId = uploadedByUserId;
    this.uploadedAt = uploadedAt;
  }
}
