// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.24.4

import { Writer, Reader } from "as-proto/assembly";

export class CompanyMembershipProto {
  static encode(message: CompanyMembershipProto, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.id);

    writer.uint32(18);
    writer.string(message.companyId);

    writer.uint32(26);
    writer.string(message.userId);

    writer.uint32(34);
    writer.string(message.role);

    writer.uint32(42);
    writer.string(message.department);

    writer.uint32(50);
    writer.string(message.position);

    writer.uint32(58);
    writer.string(message.dateJoined);

    writer.uint32(64);
    writer.bool(message.isPrimary);
  }

  static decode(reader: Reader, length: i32): CompanyMembershipProto {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new CompanyMembershipProto();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.id = reader.string();
          break;

        case 2:
          message.companyId = reader.string();
          break;

        case 3:
          message.userId = reader.string();
          break;

        case 4:
          message.role = reader.string();
          break;

        case 5:
          message.department = reader.string();
          break;

        case 6:
          message.position = reader.string();
          break;

        case 7:
          message.dateJoined = reader.string();
          break;

        case 8:
          message.isPrimary = reader.bool();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  id: string;
  companyId: string;
  userId: string;
  role: string;
  department: string;
  position: string;
  dateJoined: string;
  isPrimary: bool;

  constructor(
    id: string = "",
    companyId: string = "",
    userId: string = "",
    role: string = "",
    department: string = "",
    position: string = "",
    dateJoined: string = "",
    isPrimary: bool = false
  ) {
    this.id = id;
    this.companyId = companyId;
    this.userId = userId;
    this.role = role;
    this.department = department;
    this.position = position;
    this.dateJoined = dateJoined;
    this.isPrimary = isPrimary;
  }
}
