// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.24.4

import { Writer, Reader } from "as-proto/assembly";
import { CompanyProto } from "./CompanyProto";

export class CompanyCollection {
  static encode(message: CompanyCollection, writer: Writer): void {
    const companies = message.companies;
    for (let i: i32 = 0; i < companies.length; ++i) {
      writer.uint32(10);
      writer.fork();
      CompanyProto.encode(companies[i], writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): CompanyCollection {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new CompanyCollection();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.companies.push(CompanyProto.decode(reader, reader.uint32()));
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  companies: Array<CompanyProto>;

  constructor(companies: Array<CompanyProto> = []) {
    this.companies = companies;
  }
}
