// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.24.4

import { Writer, Reader } from "as-proto/assembly";
import { CompanyMembershipProto } from "./CompanyMembershipProto";

export class CompanyMembershipCollection {
  static encode(message: CompanyMembershipCollection, writer: Writer): void {
    const memberships = message.memberships;
    for (let i: i32 = 0; i < memberships.length; ++i) {
      writer.uint32(10);
      writer.fork();
      CompanyMembershipProto.encode(memberships[i], writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): CompanyMembershipCollection {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new CompanyMembershipCollection();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.memberships.push(
            CompanyMembershipProto.decode(reader, reader.uint32())
          );
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  memberships: Array<CompanyMembershipProto>;

  constructor(memberships: Array<CompanyMembershipProto> = []) {
    this.memberships = memberships;
  }
}
