// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.24.4

import { Writer, Reader } from "as-proto/assembly";
import { CompanyDocumentProto } from "./CompanyDocumentProto";

export class CompanyDocumentCollection {
  static encode(message: CompanyDocumentCollection, writer: Writer): void {
    const documents = message.documents;
    for (let i: i32 = 0; i < documents.length; ++i) {
      writer.uint32(10);
      writer.fork();
      CompanyDocumentProto.encode(documents[i], writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): CompanyDocumentCollection {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new CompanyDocumentCollection();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.documents.push(
            CompanyDocumentProto.decode(reader, reader.uint32())
          );
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  documents: Array<CompanyDocumentProto>;

  constructor(documents: Array<CompanyDocumentProto> = []) {
    this.documents = documents;
  }
}
