// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.24.4

import { Writer, Reader } from "as-proto/assembly";
import { AuditLogProto } from "./AuditLogProto";

export class AuditLogCollection {
  static encode(message: AuditLogCollection, writer: Writer): void {
    const auditLogs = message.auditLogs;
    for (let i: i32 = 0; i < auditLogs.length; ++i) {
      writer.uint32(10);
      writer.fork();
      AuditLogProto.encode(auditLogs[i], writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): AuditLogCollection {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new AuditLogCollection();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.auditLogs.push(AuditLogProto.decode(reader, reader.uint32()));
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  auditLogs: Array<AuditLogProto>;

  constructor(auditLogs: Array<AuditLogProto> = []) {
    this.auditLogs = auditLogs;
  }
}
