// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.24.4

import { Writer, Reader } from "as-proto/assembly";

export class AuditLogProto {
  static encode(message: AuditLogProto, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.id);

    writer.uint32(18);
    writer.string(message.userId);

    writer.uint32(26);
    writer.string(message.action);

    writer.uint32(34);
    writer.string(message.objectType);

    writer.uint32(42);
    writer.string(message.objectId);

    writer.uint32(50);
    writer.string(message.message);

    writer.uint32(58);
    writer.string(message.ipAddress);

    writer.uint32(66);
    writer.string(message.timestamp);
  }

  static decode(reader: Reader, length: i32): AuditLogProto {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new AuditLogProto();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.id = reader.string();
          break;

        case 2:
          message.userId = reader.string();
          break;

        case 3:
          message.action = reader.string();
          break;

        case 4:
          message.objectType = reader.string();
          break;

        case 5:
          message.objectId = reader.string();
          break;

        case 6:
          message.message = reader.string();
          break;

        case 7:
          message.ipAddress = reader.string();
          break;

        case 8:
          message.timestamp = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  id: string;
  userId: string;
  action: string;
  objectType: string;
  objectId: string;
  message: string;
  ipAddress: string;
  timestamp: string;

  constructor(
    id: string = "",
    userId: string = "",
    action: string = "",
    objectType: string = "",
    objectId: string = "",
    message: string = "",
    ipAddress: string = "",
    timestamp: string = ""
  ) {
    this.id = id;
    this.userId = userId;
    this.action = action;
    this.objectType = objectType;
    this.objectId = objectId;
    this.message = message;
    this.ipAddress = ipAddress;
    this.timestamp = timestamp;
  }
}
