
# Stub file for users.templatetags.user_tags

from django import template

register = template.Library()

def full_name_or_username(user: object) -> str: ...
def profile_image_url(user: object) -> str: ...
def user_role(user: object) -> str: ...
def auth_user_display(user: object) -> str: ...
def auth_status_badge(user: object) -> str: ...
def has_verified_email(user: object) -> bool: ...
def login_url_with_next(context: object) -> str: ...
