from _typeshed import Incomplete

STATUS_NOT_STARTED: str
STATUS_IN_PROGRESS: str
STATUS_COMPLETED: str
STATUS_OVERDUE: str
STATUS_UPCOMING: str
STATUS_CHOICES: list[tuple[str, str]]
DUE_PERIOD_OVERDUE: str
DUE_PERIOD_THIS_WEEK: str
DUE_PERIOD_NEXT_WEEK: str
DUE_PERIOD_THIS_MONTH: str
DUE_PERIOD_NEXT_MONTH: str
FREQUENCY_DAILY: str
FREQUENCY_WEEKLY: str
FREQUENCY_FORTNIGHTLY: str
FREQUENCY_MONTHLY: str
FREQUENCY_QUARTERLY: str
FREQUENCY_BIANNUAL: str
FREQUENCY_ANNUAL: str
FREQUENCY_SEMI_ANNUAL: str
FREQUENCY_BI_ANNUALLY: str
FREQUENCY_YEARLY: str
FREQUENCY_ANNUALLY: str
FREQUENCY_DISPLAY_NAMES: Incomplete
FREQUENCY_CHOICES: list[tuple[str, str]]
FREQUENCY_ALIASES: Incomplete
FREQUENCY_DAYS: Incomplete
