from .models import Obligation
from _typeshed import Incomplete
from datetime import date
from typing import Any

logger: Incomplete

def is_obligation_overdue(obligation: Obligation | dict[str, Any], reference_date: date | None = None) -> bool: ...
def get_obligation_status(obligation): ...
def _match_frequency_pattern(frequency_lower: str) -> str | None: ...
def normalize_frequency(frequency: str) -> str: ...
def get_responsibility_display_name(responsibility_value: str) -> str: ...
