from .forms import ObligationForm
from .models import Obligation
from _typeshed import Incomplete
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import QuerySet
from django.http import HttpRequest as HttpRequest
from django.views import View
from django.views.generic import CreateView, DetailView, ListView, UpdateView
from django.views.generic.edit import DeleteView
from mechanisms.models import EnvironmentalMechanism
from typing import Any

logger: Incomplete

class ObligationSummaryView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs): ...
    def _filter_by_status(self, queryset: QuerySet, status_values: list) -> QuerySet: ...
    def apply_filters(self, queryset: QuerySet, filters: dict[str, Any]) -> QuerySet: ...
    def get_filters(self) -> dict[str, Any]: ...
    def get_context_data(self, **kwargs): ...

class TotalOverdueObligationsView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs): ...

class ObligationCreateView(LoginRequiredMixin, CreateView):
    model = Obligation
    form_class = ObligationForm
    template_name: str
    def get_form_kwargs(self): ...
    def get_context_data(self, **kwargs): ...
    def form_valid(self, form): ...
    def form_invalid(self, form): ...

class ObligationDetailView(LoginRequiredMixin, DetailView):
    model = Obligation
    template_name: str
    context_object_name: str
    pk_url_kwarg: str
    def get_context_data(self, **kwargs): ...

class ObligationUpdateView(LoginRequiredMixin, UpdateView):
    model = Obligation
    form_class = ObligationForm
    template_name: str
    slug_field: str
    slug_url_kwarg: str
    def get_template_names(self): ...
    def get_form_kwargs(self): ...
    def get_context_data(self, **kwargs): ...
    def _update_mechanism_counts(self, old_mechanism: EnvironmentalMechanism, updated_obligation: Obligation): ...
    def form_valid(self, form): ...
    def form_invalid(self, form): ...

class ObligationDeleteView(LoginRequiredMixin, DeleteView):
    model = Obligation
    pk_url_kwarg: str
    object: Incomplete
    def post(self, request, *args, **kwargs): ...

class ToggleCustomAspectView(View):
    def get(self, request): ...

class ObligationListView(LoginRequiredMixin, ListView):
    model = Obligation
    template_name: str
    context_object_name: str
    paginate_by: int
    def get_queryset(self): ...
    def get_context_data(self, **kwargs): ...

def upload_evidence(request, obligation_id): ...
def obligation_list_popup(request): ...
