from _typeshed import Incomplete
from django.db.models import QuerySet
from matplotlib.axes import Axes
from matplotlib.figure import Figure
from typing import Any

logger: Incomplete

def generate_procedure_statistics(project_slug: str | None = None) -> tuple[Figure, dict[str, Any]]: ...
def _calculate_procedure_statistics(procedures: QuerySet) -> dict[str, Any]: ...
def _plot_procedure_status_chart(ax: Axes, stats: dict[str, Any]) -> None: ...
def _plot_procedure_timeline_chart(ax: Axes, stats: dict[str, Any]) -> None: ...
def get_procedure_charts(mechanism_id: str | int, filtered_ids: list[int] | None = None) -> dict[str, Figure]: ...
def _get_status_counts(obligations: QuerySet) -> dict[str, int]: ...
def _create_pie_chart(title: str, status_counts: dict[str, int]) -> Figure: ...
def _create_empty_chart(title: str) -> Figure: ...
def _create_error_chart(error_message: str) -> Figure: ...
def get_all_procedure_charts() -> dict[str, bytes]: ...
def chart_to_png(fig: Figure) -> bytes: ...
def get_procedure_status_chart() -> Figure: ...
def get_procedure_timeline() -> Figure: ...
def get_completion_rate_chart() -> Figure: ...
