from .models import Procedure
from _typeshed import Incomplete
from django.contrib.auth.mixins import LoginRequiredMixin
from django.template.loader import render_to_string as render_to_string
from django.views.generic import ListView, TemplateView
from typing import Any

logger: Incomplete

class ProcedureChartsView(LoginRequiredMixin, TemplateView):
    template_name: str
    def get_template_names(self): ...
    def _get_mechanism_and_obligations(self, mechanism_id): ...
    def _apply_filters(self, obligations, request_params): ...
    def _calculate_statistics(self, all_obligations): ...
    def _get_available_filters(self, all_obligations): ...
    def _generate_responsibility_chart(self, mechanism_id, filtered_obligations: Incomplete | None = None, filters_applied: bool = False): ...
    def _generate_procedure_charts(self, mechanism_id, filtered_obligations, all_obligations, filters_applied): ...
    def _create_procedure_chart_data(self, procedure_name, obligations): ...
    def get_context_data(self, **kwargs) -> dict[str, Any]: ...

class ProcedureListView(LoginRequiredMixin, ListView):
    model = Procedure
    template_name: str
    context_object_name: str
    def get_queryset(self): ...
