from typing import Final

STATUS_NOT_STARTED: Final[str]
STATUS_IN_PROGRESS: Final[str]
STATUS_COMPLETED: Final[str]
STATUS_OVERDUE: Final[str]
STATUS_UPCOMING: Final[str]

STATUS_CHOICES: Final[list[tuple[str, str]]]
OBLIGATION_STATUS_CHOICES: Final[list[tuple[str, str]]]

DUE_PERIOD_OVERDUE: Final[str]
DUE_PERIOD_THIS_WEEK: Final[str]
DUE_PERIOD_NEXT_WEEK: Final[str]
DUE_PERIOD_THIS_MONTH: Final[str]
DUE_PERIOD_NEXT_MONTH: Final[str]

FREQUENCY_DAILY: Final[str]
FREQUENCY_WEEKLY: Final[str]
FREQUENCY_MONTHLY: Final[str]
FREQUENCY_QUARTERLY: Final[str]
FREQUENCY_ANNUALLY: Final[str]

FREQUENCY_CHOICES: Final[list[tuple[str, str]]]

ROLE_OWNER: str
ROLE_MANAGER: str
ROLE_MEMBER: str
ROLE_VIEWER: str
ROLE_CHOICES: list[tuple[str, str]]
MECHANISM_STATUS_COLORS: dict[str, str]
MECHANISM_TYPE_PHYSICAL: Final[str]
MECHANISM_TYPE_CHEMICAL: Final[str]
MECHANISM_TYPE_BIOLOGICAL: Final[str]
MECHANISM_TYPE_OTHER: Final[str]
MECHANISM_TYPE_CHOICES: Final[list[tuple[str, str]]]
MECHANISM_CATEGORY_PREVENTION: Final[str]
MECHANISM_CATEGORY_CONTROL: Final[str]
MECHANISM_CATEGORY_MITIGATION: Final[str]
MECHANISM_CATEGORY_CHOICES: Final[list[tuple[str, str]]]
OPERATIONAL_MODE_AUTOMATIC: Final[str]
OPERATIONAL_MODE_MANUAL: Final[str]
OPERATIONAL_MODE_CHOICES: Final[list[tuple[str, str]]]
