# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mechanism.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fmechanism.proto\x12\x13greenova.mechanisms\"X\n\x11ObligationInsight\x12\x19\n\x11obligation_number\x18\x01 \x01(\t\x12\x10\n\x08\x64ue_date\x18\x02 \x01(\t\x12\x16\n\x0e\x63lose_out_date\x18\x03 \x01(\t\"\xc5\x01\n\x19ObligationInsightResponse\x12\x14\n\x0cmechanism_id\x18\x01 \x01(\x05\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x12\n\nstatus_key\x18\x03 \x01(\t\x12\r\n\x05\x63ount\x18\x04 \x01(\x05\x12\x13\n\x0btotal_count\x18\x05 \x01(\x05\x12;\n\x0bobligations\x18\x06 \x03(\x0b\x32&.greenova.mechanisms.ObligationInsight\x12\r\n\x05\x65rror\x18\x07 \x01(\t\";\n\x0c\x43hartSegment\x12\r\n\x05label\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05\x12\r\n\x05\x63olor\x18\x03 \x01(\t\"n\n\tChartData\x12\x33\n\x08segments\x18\x01 \x03(\x0b\x32!.greenova.mechanisms.ChartSegment\x12\x14\n\x0cmechanism_id\x18\x02 \x01(\x05\x12\x16\n\x0emechanism_name\x18\x03 \x01(\t\"N\n\rChartResponse\x12.\n\x06\x63harts\x18\x01 \x03(\x0b\x32\x1e.greenova.mechanisms.ChartData\x12\r\n\x05\x65rror\x18\x02 \x01(\t*\x80\x01\n\x10ObligationStatus\x12\x12\n\x0eSTATUS_UNKNOWN\x10\x00\x12\x16\n\x12STATUS_NOT_STARTED\x10\x01\x12\x16\n\x12STATUS_IN_PROGRESS\x10\x02\x12\x14\n\x10STATUS_COMPLETED\x10\x03\x12\x12\n\x0eSTATUS_OVERDUE\x10\x04\x42.\n\x17\x63om.greenova.mechanismsZ\x13greenova/mechanismsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mechanism_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\027com.greenova.mechanismsZ\023greenova/mechanisms'
  _globals['_OBLIGATIONSTATUS']._serialized_start=584
  _globals['_OBLIGATIONSTATUS']._serialized_end=712
  _globals['_OBLIGATIONINSIGHT']._serialized_start=40
  _globals['_OBLIGATIONINSIGHT']._serialized_end=128
  _globals['_OBLIGATIONINSIGHTRESPONSE']._serialized_start=131
  _globals['_OBLIGATIONINSIGHTRESPONSE']._serialized_end=328
  _globals['_CHARTSEGMENT']._serialized_start=330
  _globals['_CHARTSEGMENT']._serialized_end=389
  _globals['_CHARTDATA']._serialized_start=391
  _globals['_CHARTDATA']._serialized_end=501
  _globals['_CHARTRESPONSE']._serialized_start=503
  _globals['_CHARTRESPONSE']._serialized_end=581
# @@protoc_insertion_point(module_scope)
