// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.24.4

import { Writer, Reader } from "as-proto/assembly";

export class ComplianceByFramework {
  static encode(message: ComplianceByFramework, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.frameworkName);

    writer.uint32(17);
    writer.double(message.complianceRate);

    writer.uint32(24);
    writer.int32(message.totalObligations);

    writer.uint32(32);
    writer.int32(message.compliantObligations);
  }

  static decode(reader: Reader, length: i32): ComplianceByFramework {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new ComplianceByFramework();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.frameworkName = reader.string();
          break;

        case 2:
          message.complianceRate = reader.double();
          break;

        case 3:
          message.totalObligations = reader.int32();
          break;

        case 4:
          message.compliantObligations = reader.int32();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  frameworkName: string;
  complianceRate: f64;
  totalObligations: i32;
  compliantObligations: i32;

  constructor(
    frameworkName: string = "",
    complianceRate: f64 = 0.0,
    totalObligations: i32 = 0,
    compliantObligations: i32 = 0
  ) {
    this.frameworkName = frameworkName;
    this.complianceRate = complianceRate;
    this.totalObligations = totalObligations;
    this.compliantObligations = compliantObligations;
  }
}
