// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.24.4

import { Writer, Reader } from "as-proto/assembly";
import { ComplianceByFramework } from "./ComplianceByFramework";

export class ComplianceMetrics {
  static encode(message: ComplianceMetrics, writer: Writer): void {
    writer.uint32(9);
    writer.double(message.overallComplianceRate);

    writer.uint32(16);
    writer.int32(message.overdueObligations);

    writer.uint32(24);
    writer.int32(message.dueThisWeek);

    writer.uint32(32);
    writer.int32(message.dueThisMonth);

    const complianceByFramework = message.complianceByFramework;
    for (let i: i32 = 0; i < complianceByFramework.length; ++i) {
      writer.uint32(42);
      writer.fork();
      ComplianceByFramework.encode(complianceByFramework[i], writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): ComplianceMetrics {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new ComplianceMetrics();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.overallComplianceRate = reader.double();
          break;

        case 2:
          message.overdueObligations = reader.int32();
          break;

        case 3:
          message.dueThisWeek = reader.int32();
          break;

        case 4:
          message.dueThisMonth = reader.int32();
          break;

        case 5:
          message.complianceByFramework.push(
            ComplianceByFramework.decode(reader, reader.uint32())
          );
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  overallComplianceRate: f64;
  overdueObligations: i32;
  dueThisWeek: i32;
  dueThisMonth: i32;
  complianceByFramework: Array<ComplianceByFramework>;

  constructor(
    overallComplianceRate: f64 = 0.0,
    overdueObligations: i32 = 0,
    dueThisWeek: i32 = 0,
    dueThisMonth: i32 = 0,
    complianceByFramework: Array<ComplianceByFramework> = []
  ) {
    this.overallComplianceRate = overallComplianceRate;
    this.overdueObligations = overdueObligations;
    this.dueThisWeek = dueThisWeek;
    this.dueThisMonth = dueThisMonth;
    this.complianceByFramework = complianceByFramework;
  }
}
