// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.24.4

import { Writer, Reader } from "as-proto/assembly";
import { ProjectSummary } from "./ProjectSummary";
import { ObligationSummary } from "./ObligationSummary";
import { ComplianceMetrics } from "./ComplianceMetrics";

export class DashboardData {
  static encode(message: DashboardData, writer: Writer): void {
    const projectSummary = message.projectSummary;
    if (projectSummary !== null) {
      writer.uint32(10);
      writer.fork();
      ProjectSummary.encode(projectSummary, writer);
      writer.ldelim();
    }

    const obligationSummaries = message.obligationSummaries;
    for (let i: i32 = 0; i < obligationSummaries.length; ++i) {
      writer.uint32(18);
      writer.fork();
      ObligationSummary.encode(obligationSummaries[i], writer);
      writer.ldelim();
    }

    const complianceMetrics = message.complianceMetrics;
    if (complianceMetrics !== null) {
      writer.uint32(26);
      writer.fork();
      ComplianceMetrics.encode(complianceMetrics, writer);
      writer.ldelim();
    }

    writer.uint32(32);
    writer.int64(message.lastUpdated);
  }

  static decode(reader: Reader, length: i32): DashboardData {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new DashboardData();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.projectSummary = ProjectSummary.decode(
            reader,
            reader.uint32()
          );
          break;

        case 2:
          message.obligationSummaries.push(
            ObligationSummary.decode(reader, reader.uint32())
          );
          break;

        case 3:
          message.complianceMetrics = ComplianceMetrics.decode(
            reader,
            reader.uint32()
          );
          break;

        case 4:
          message.lastUpdated = reader.int64();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  projectSummary: ProjectSummary | null;
  obligationSummaries: Array<ObligationSummary>;
  complianceMetrics: ComplianceMetrics | null;
  lastUpdated: i64;

  constructor(
    projectSummary: ProjectSummary | null = null,
    obligationSummaries: Array<ObligationSummary> = [],
    complianceMetrics: ComplianceMetrics | null = null,
    lastUpdated: i64 = 0
  ) {
    this.projectSummary = projectSummary;
    this.obligationSummaries = obligationSummaries;
    this.complianceMetrics = complianceMetrics;
    this.lastUpdated = lastUpdated;
  }
}
