// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.24.4

import { Writer, Reader } from "as-proto/assembly";
import { Requirement } from "./Requirement";

export class Obligation {
  static encode(message: Obligation, writer: Writer): void {
    writer.uint32(8);
    writer.int32(message.id);

    writer.uint32(18);
    writer.string(message.title);

    writer.uint32(26);
    writer.string(message.description);

    writer.uint32(34);
    writer.string(message.status);

    writer.uint32(42);
    writer.string(message.dueDate);

    writer.uint32(48);
    writer.int32(message.projectId);

    const requirements = message.requirements;
    for (let i: i32 = 0; i < requirements.length; ++i) {
      writer.uint32(58);
      writer.fork();
      Requirement.encode(requirements[i], writer);
      writer.ldelim();
    }

    writer.uint32(64);
    writer.int64(message.createdAt);

    writer.uint32(72);
    writer.int64(message.updatedAt);
  }

  static decode(reader: Reader, length: i32): Obligation {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new Obligation();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.id = reader.int32();
          break;

        case 2:
          message.title = reader.string();
          break;

        case 3:
          message.description = reader.string();
          break;

        case 4:
          message.status = reader.string();
          break;

        case 5:
          message.dueDate = reader.string();
          break;

        case 6:
          message.projectId = reader.int32();
          break;

        case 7:
          message.requirements.push(
            Requirement.decode(reader, reader.uint32())
          );
          break;

        case 8:
          message.createdAt = reader.int64();
          break;

        case 9:
          message.updatedAt = reader.int64();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  id: i32;
  title: string;
  description: string;
  status: string;
  dueDate: string;
  projectId: i32;
  requirements: Array<Requirement>;
  createdAt: i64;
  updatedAt: i64;

  constructor(
    id: i32 = 0,
    title: string = "",
    description: string = "",
    status: string = "",
    dueDate: string = "",
    projectId: i32 = 0,
    requirements: Array<Requirement> = [],
    createdAt: i64 = 0,
    updatedAt: i64 = 0
  ) {
    this.id = id;
    this.title = title;
    this.description = description;
    this.status = status;
    this.dueDate = dueDate;
    this.projectId = projectId;
    this.requirements = requirements;
    this.createdAt = createdAt;
    this.updatedAt = updatedAt;
  }
}
