// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.24.4

import { Writer, Reader } from "as-proto/assembly";
import { Obligation } from "./Obligation";

export class ObligationSummary {
  static encode(message: ObligationSummary, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.status);

    writer.uint32(16);
    writer.int32(message.count);

    const upcomingObligations = message.upcomingObligations;
    for (let i: i32 = 0; i < upcomingObligations.length; ++i) {
      writer.uint32(26);
      writer.fork();
      Obligation.encode(upcomingObligations[i], writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): ObligationSummary {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new ObligationSummary();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.status = reader.string();
          break;

        case 2:
          message.count = reader.int32();
          break;

        case 3:
          message.upcomingObligations.push(
            Obligation.decode(reader, reader.uint32())
          );
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  status: string;
  count: i32;
  upcomingObligations: Array<Obligation>;

  constructor(
    status: string = "",
    count: i32 = 0,
    upcomingObligations: Array<Obligation> = []
  ) {
    this.status = status;
    this.count = count;
    this.upcomingObligations = upcomingObligations;
  }
}
