// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.24.4

import { Writer, Reader } from "as-proto/assembly";

export class ProjectMetadata {
  static encode(message: ProjectMetadata, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.environmentalZone);

    const complianceFrameworks = message.complianceFrameworks;
    if (complianceFrameworks.length !== 0) {
      for (let i: i32 = 0; i < complianceFrameworks.length; ++i) {
        writer.uint32(18);
        writer.string(complianceFrameworks[i]);
      }
    }

    writer.uint32(26);
    writer.string(message.projectManager);

    writer.uint32(34);
    writer.string(message.contactEmail);
  }

  static decode(reader: Reader, length: i32): ProjectMetadata {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new ProjectMetadata();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.environmentalZone = reader.string();
          break;

        case 2:
          message.complianceFrameworks.push(reader.string());
          break;

        case 3:
          message.projectManager = reader.string();
          break;

        case 4:
          message.contactEmail = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  environmentalZone: string;
  complianceFrameworks: Array<string>;
  projectManager: string;
  contactEmail: string;

  constructor(
    environmentalZone: string = "",
    complianceFrameworks: Array<string> = [],
    projectManager: string = "",
    contactEmail: string = ""
  ) {
    this.environmentalZone = environmentalZone;
    this.complianceFrameworks = complianceFrameworks;
    this.projectManager = projectManager;
    this.contactEmail = contactEmail;
  }
}
