// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.24.4

import { Writer, Reader } from "as-proto/assembly";
import { Obligation } from "./Obligation";
import { ProjectMetadata } from "./ProjectMetadata";

export class Project {
  static encode(message: Project, writer: Writer): void {
    writer.uint32(8);
    writer.int32(message.id);

    writer.uint32(18);
    writer.string(message.name);

    writer.uint32(26);
    writer.string(message.description);

    writer.uint32(34);
    writer.string(message.location);

    const obligations = message.obligations;
    for (let i: i32 = 0; i < obligations.length; ++i) {
      writer.uint32(42);
      writer.fork();
      Obligation.encode(obligations[i], writer);
      writer.ldelim();
    }

    const metadata = message.metadata;
    if (metadata !== null) {
      writer.uint32(50);
      writer.fork();
      ProjectMetadata.encode(metadata, writer);
      writer.ldelim();
    }

    writer.uint32(56);
    writer.int64(message.createdAt);

    writer.uint32(64);
    writer.int64(message.updatedAt);
  }

  static decode(reader: Reader, length: i32): Project {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new Project();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.id = reader.int32();
          break;

        case 2:
          message.name = reader.string();
          break;

        case 3:
          message.description = reader.string();
          break;

        case 4:
          message.location = reader.string();
          break;

        case 5:
          message.obligations.push(Obligation.decode(reader, reader.uint32()));
          break;

        case 6:
          message.metadata = ProjectMetadata.decode(reader, reader.uint32());
          break;

        case 7:
          message.createdAt = reader.int64();
          break;

        case 8:
          message.updatedAt = reader.int64();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  id: i32;
  name: string;
  description: string;
  location: string;
  obligations: Array<Obligation>;
  metadata: ProjectMetadata | null;
  createdAt: i64;
  updatedAt: i64;

  constructor(
    id: i32 = 0,
    name: string = "",
    description: string = "",
    location: string = "",
    obligations: Array<Obligation> = [],
    metadata: ProjectMetadata | null = null,
    createdAt: i64 = 0,
    updatedAt: i64 = 0
  ) {
    this.id = id;
    this.name = name;
    this.description = description;
    this.location = location;
    this.obligations = obligations;
    this.metadata = metadata;
    this.createdAt = createdAt;
    this.updatedAt = updatedAt;
  }
}
