// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.24.4

import { Writer, Reader } from "as-proto/assembly";
import { Project } from "./Project";

export class ProjectSummary {
  static encode(message: ProjectSummary, writer: Writer): void {
    writer.uint32(8);
    writer.int32(message.totalProjects);

    writer.uint32(16);
    writer.int32(message.activeProjects);

    writer.uint32(24);
    writer.int32(message.completedProjects);

    const recentProjects = message.recentProjects;
    for (let i: i32 = 0; i < recentProjects.length; ++i) {
      writer.uint32(34);
      writer.fork();
      Project.encode(recentProjects[i], writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): ProjectSummary {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new ProjectSummary();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.totalProjects = reader.int32();
          break;

        case 2:
          message.activeProjects = reader.int32();
          break;

        case 3:
          message.completedProjects = reader.int32();
          break;

        case 4:
          message.recentProjects.push(Project.decode(reader, reader.uint32()));
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  totalProjects: i32;
  activeProjects: i32;
  completedProjects: i32;
  recentProjects: Array<Project>;

  constructor(
    totalProjects: i32 = 0,
    activeProjects: i32 = 0,
    completedProjects: i32 = 0,
    recentProjects: Array<Project> = []
  ) {
    this.totalProjects = totalProjects;
    this.activeProjects = activeProjects;
    this.completedProjects = completedProjects;
    this.recentProjects = recentProjects;
  }
}
