// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.24.4

import { Writer, Reader } from "as-proto/assembly";

export class Requirement {
  static encode(message: Requirement, writer: Writer): void {
    writer.uint32(8);
    writer.int32(message.id);

    writer.uint32(18);
    writer.string(message.name);

    writer.uint32(26);
    writer.string(message.description);

    writer.uint32(34);
    writer.string(message.complianceStatus);

    const tags = message.tags;
    if (tags.length !== 0) {
      for (let i: i32 = 0; i < tags.length; ++i) {
        writer.uint32(42);
        writer.string(tags[i]);
      }
    }
  }

  static decode(reader: Reader, length: i32): Requirement {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new Requirement();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.id = reader.int32();
          break;

        case 2:
          message.name = reader.string();
          break;

        case 3:
          message.description = reader.string();
          break;

        case 4:
          message.complianceStatus = reader.string();
          break;

        case 5:
          message.tags.push(reader.string());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  id: i32;
  name: string;
  description: string;
  complianceStatus: string;
  tags: Array<string>;

  constructor(
    id: i32 = 0,
    name: string = "",
    description: string = "",
    complianceStatus: string = "",
    tags: Array<string> = []
  ) {
    this.id = id;
    this.name = name;
    this.description = description;
    this.complianceStatus = complianceStatus;
    this.tags = tags;
  }
}
