
# Stub file for responsibility.templatetags.responsibility_tags

from django import template

register = template.Library()

def user_has_responsibility(user: object, obligation: object) -> bool: ...
def user_responsibility_roles(user: object, obligation: object) -> list: ...
def format_responsibility_roles(roles: object) -> str: ...
def get_responsible_users(obligation: object) -> list: ...
