from _typeshed import Incomplete

logger: Incomplete
register: Incomplete

def active_link(context, url_name, css_class: str = 'active'): ...
def breadcrumb_navigation(context): ...
def auth_menu(context): ...
def theme_switcher(): ...
@register.simple_tag
def site_version(): ...
def main_navigation(context): ...
@register.filter
def user_role_in_project(project, user): ...
def base_url(context): ...
def format_date(date_value, format_string: str = '%d %b %Y'): ...
