from typing import Any

class ChartData:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def SerializeToString(self) -> bytes: ...
    chart_id: str
    chart_type: str
    title: str
    config: Any
    data_series: Any
    metadata: Any

class DataSeries: ...
class DataPoint: ...
class ChartMetadata: ...
