# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/chatbot.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16protobuf/chatbot.proto\x12\x07\x63hatbot\"\xd4\x01\n\x0b\x43hatMessage\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x12.\n\x04type\x18\x04 \x01(\x0e\x32 .chatbot.ChatMessage.MessageType\"`\n\x0bMessageType\x12!\n\x1dMESSAGE_TYPE_TEXT_UNSPECIFIED\x10\x00\x12\x16\n\x12MESSAGE_TYPE_IMAGE\x10\x01\x12\x16\n\x12MESSAGE_TYPE_AUDIO\x10\x02\"F\n\x0c\x43hatResponse\x12\x12\n\nmessage_id\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protobuf.chatbot_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CHATMESSAGE']._serialized_start=36
  _globals['_CHATMESSAGE']._serialized_end=248
  _globals['_CHATMESSAGE_MESSAGETYPE']._serialized_start=152
  _globals['_CHATMESSAGE_MESSAGETYPE']._serialized_end=248
  _globals['_CHATRESPONSE']._serialized_start=250
  _globals['_CHATRESPONSE']._serialized_end=320
# @@protoc_insertion_point(module_scope)
