# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/core_audit.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19protobuf/core_audit.proto\x12\ncore_audit\"\x9c\x01\n\rAuditLogProto\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x03 \x01(\t\x12\x13\n\x0bobject_type\x18\x04 \x01(\t\x12\x11\n\tobject_id\x18\x05 \x01(\t\x12\x0f\n\x07message\x18\x06 \x01(\t\x12\x12\n\nip_address\x18\x07 \x01(\t\x12\x11\n\ttimestamp\x18\x08 \x01(\t\"C\n\x12\x41uditLogCollection\x12-\n\naudit_logs\x18\x01 \x03(\x0b\x32\x19.core_audit.AuditLogProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protobuf.core_audit_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_AUDITLOGPROTO']._serialized_start=42
  _globals['_AUDITLOGPROTO']._serialized_end=198
  _globals['_AUDITLOGCOLLECTION']._serialized_start=200
  _globals['_AUDITLOGCOLLECTION']._serialized_end=267
# @@protoc_insertion_point(module_scope)
