# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/dashboard.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18protobuf/dashboard.proto\x12\tdashboard\"N\n\x0f\x44\x61shboardWidget\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\t\x12\x13\n\x0b\x63onfig_json\x18\x04 \x01(\t\"S\n\x0f\x44\x61shboardLayout\x12+\n\x07widgets\x18\x01 \x03(\x0b\x32\x1a.dashboard.DashboardWidget\x12\x13\n\x0blayout_json\x18\x02 \x01(\t\"w\n\x14\x44\x61shboardPreferences\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x18\n\x10selected_project\x18\x02 \x01(\t\x12\x1a\n\x12selected_mechanism\x18\x03 \x01(\t\x12\x18\n\x10preferences_json\x18\x04 \x01(\t\"\x8e\x01\n\x14\x44\x61shboardAPIResponse\x12*\n\x06layout\x18\x01 \x01(\x0b\x32\x1a.dashboard.DashboardLayout\x12\x34\n\x0bpreferences\x18\x02 \x01(\x0b\x32\x1f.dashboard.DashboardPreferences\x12\x14\n\x0clast_updated\x18\x03 \x01(\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protobuf.dashboard_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DASHBOARDWIDGET']._serialized_start=39
  _globals['_DASHBOARDWIDGET']._serialized_end=117
  _globals['_DASHBOARDLAYOUT']._serialized_start=119
  _globals['_DASHBOARDLAYOUT']._serialized_end=202
  _globals['_DASHBOARDPREFERENCES']._serialized_start=204
  _globals['_DASHBOARDPREFERENCES']._serialized_end=323
  _globals['_DASHBOARDAPIRESPONSE']._serialized_start=326
  _globals['_DASHBOARDAPIRESPONSE']._serialized_end=468
# @@protoc_insertion_point(module_scope)
