from typing import Any

class DashboardData:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def SerializeToString(self) -> bytes: ...
    project_summary: Any
    obligation_summaries: Any
    compliance_metrics: Any
    last_updated: int

class ProjectSummary: ...
class ObligationSummary: ...
class ComplianceMetrics: ...
