# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/obligations.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aprotobuf/obligations.proto\x12\x0bobligations\"\x95\x06\n\x0fObligationProto\x12\x19\n\x11obligation_number\x18\x01 \x01(\t\x12\x12\n\nproject_id\x18\x02 \x01(\t\x12*\n\"primary_environmental_mechanism_id\x18\x03 \x01(\t\x12\x11\n\tprocedure\x18\x04 \x01(\t\x12\x1c\n\x14\x65nvironmental_aspect\x18\x05 \x01(\t\x12#\n\x1b\x63ustom_environmental_aspect\x18\x06 \x01(\t\x12\x12\n\nobligation\x18\x07 \x01(\t\x12\x16\n\x0e\x61\x63\x63ountability\x18\x08 \x01(\t\x12\x1c\n\x14responsible_user_ids\x18\t \x03(\t\x12\x15\n\rproject_phase\x18\n \x01(\t\x12\x17\n\x0f\x61\x63tion_due_date\x18\x0b \x01(\t\x12\x16\n\x0e\x63lose_out_date\x18\x0c \x01(\t\x12\x0e\n\x06status\x18\r \x01(\t\x12\x1e\n\x16supporting_information\x18\x0e \x01(\t\x12\x18\n\x10general_comments\x18\x0f \x01(\t\x12\x16\n\x0e\x65vidence_notes\x18\x10 \x01(\t\x12\x1c\n\x14recurring_obligation\x18\x11 \x01(\x08\x12\x1b\n\x13recurring_frequency\x18\x12 \x01(\t\x12\x18\n\x10recurring_status\x18\x13 \x01(\t\x12!\n\x19recurring_forecasted_date\x18\x14 \x01(\t\x12\x12\n\ninspection\x18\x15 \x01(\x08\x12\x1c\n\x14inspection_frequency\x18\x16 \x01(\t\x12\x17\n\x0fsite_or_desktop\x18\x17 \x01(\t\x12#\n\x1bnew_control_action_required\x18\x18 \x01(\x08\x12\x17\n\x0fobligation_type\x18\x19 \x01(\t\x12\x14\n\x0cgap_analysis\x18\x1a \x01(\x08\x12\x1e\n\x16notes_for_gap_analysis\x18\x1b \x01(\t\x12\x12\n\ncreated_at\x18\x1c \x01(\t\x12\x12\n\nupdated_at\x18\x1d \x01(\t\"I\n\x14ObligationCollection\x12\x31\n\x0bobligations\x18\x01 \x03(\x0b\x32\x1c.obligations.ObligationProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protobuf.obligations_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_OBLIGATIONPROTO']._serialized_start=44
  _globals['_OBLIGATIONPROTO']._serialized_end=833
  _globals['_OBLIGATIONCOLLECTION']._serialized_start=835
  _globals['_OBLIGATIONCOLLECTION']._serialized_end=908
# @@protoc_insertion_point(module_scope)
