# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: projects.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eprojects.proto\x12\x08projects\"~\n\x0cProjectProto\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x17\n\x0fmember_user_ids\x18\x04 \x03(\t\x12\x12\n\ncreated_at\x18\x05 \x01(\t\x12\x12\n\nupdated_at\x18\x06 \x01(\t\"\x7f\n\x16ProjectMembershipProto\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\nproject_id\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\t\x12\x0c\n\x04role\x18\x04 \x01(\t\x12\x12\n\ncreated_at\x18\x05 \x01(\t\x12\x12\n\nupdated_at\x18\x06 \x01(\t\"w\n\x16ProjectObligationProto\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\nproject_id\x18\x02 \x01(\t\x12\x15\n\robligation_id\x18\x03 \x01(\t\x12\x12\n\ncreated_at\x18\x04 \x01(\t\x12\x12\n\nupdated_at\x18\x05 \x01(\t\"=\n\x11ProjectCollection\x12(\n\x08projects\x18\x01 \x03(\x0b\x32\x16.projects.ProjectProto\"T\n\x1bProjectMembershipCollection\x12\x35\n\x0bmemberships\x18\x01 \x03(\x0b\x32 .projects.ProjectMembershipProto\"\\\n\x1bProjectObligationCollection\x12=\n\x13project_obligations\x18\x01 \x03(\x0b\x32 .projects.ProjectObligationProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'projects_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PROJECTPROTO']._serialized_start=28
  _globals['_PROJECTPROTO']._serialized_end=154
  _globals['_PROJECTMEMBERSHIPPROTO']._serialized_start=156
  _globals['_PROJECTMEMBERSHIPPROTO']._serialized_end=283
  _globals['_PROJECTOBLIGATIONPROTO']._serialized_start=285
  _globals['_PROJECTOBLIGATIONPROTO']._serialized_end=404
  _globals['_PROJECTCOLLECTION']._serialized_start=406
  _globals['_PROJECTCOLLECTION']._serialized_end=467
  _globals['_PROJECTMEMBERSHIPCOLLECTION']._serialized_start=469
  _globals['_PROJECTMEMBERSHIPCOLLECTION']._serialized_end=553
  _globals['_PROJECTOBLIGATIONCOLLECTION']._serialized_start=555
  _globals['_PROJECTOBLIGATIONCOLLECTION']._serialized_end=647
# @@protoc_insertion_point(module_scope)
