# Generated by Django 5.1.5 on 2025-02-07 12:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("show_completed", models.BooleanField(default=True)),
                (
                    "chart_type",
                    models.CharField(
                        choices=[("bar", "Bar"), ("line", "Line"), ("pie", "Pie")],
                        default="bar",
                        max_length=10,
                    ),
                ),
                (
                    "refresh_interval",
                    models.PositiveIntegerField(
                        default=30,
                        validators=[
                            django.core.validators.MinValueValidator(
                                10,
                                message="Refresh interval must be at least 10 seconds",
                            ),
                            django.core.validators.MaxValueValidator(
                                300,
                                message="Refresh interval cannot exceed 300 seconds",
                            ),
                        ],
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboard_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Dashboard Preference",
                "verbose_name_plural": "Dashboard Preferences",
            },
        ),
    ]
