from ..models import BugReport
from _typeshed import Incomplete
from django.db.models import QuerySet

register: Incomplete

def severity_color(severity: str) -> str: ...
def status_color(status: str) -> str: ...
@register.simple_tag
def get_open_bug_count() -> int: ...
def get_status_description(status: str) -> str: ...
def show_bug_tracker_mini() -> dict[str, QuerySet[BugReport] | int | str]: ...
