# Generated by Django 5.1.6 on 2025-02-24 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("mechanisms", "0001_initial"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="environmentalmechanism",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mechanisms",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="chartconfiguration",
            name="mechanism",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chart_config",
                to="mechanisms.environmentalmechanism",
            ),
        ),
    ]
