# Generated by Django 5.1.6 on 2025-02-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mechanisms", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="environmentalmechanism",
            name="status",
            field=models.CharField(
                choices=[
                    ("not started", "Not Started"),
                    ("in progress", "In Progress"),
                    ("completed", "Completed"),
                ],
                default="not started",
                max_length=20,
            ),
        ),
    ]
