# Generated by Django 5.1.6 on 2025-02-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mechanisms", "0002_initial"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="environmentalmechanism",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name="environmentalmechanism",
            unique_together={("name", "project")},
        ),
    ]
