# Generated by Django 5.1.6 on 2025-02-24 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mechanisms", "0004_environmentalmechanism_completed_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="environmentalmechanism",
            name="primary_environmental_mechanism",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
