# Generated by Django 5.1.6 on 2025-02-27 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mechanisms", "0005_environmentalmechanism_primary_environmental_mechanism"),
    ]

    operations = [
        migrations.AddField(
            model_name="environmentalmechanism",
            name="overdue_count",
            field=models.IntegerField(default=0),
        ),
    ]
