# Generated by Django 5.1.6 on 2025-02-28 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanisms', '0007_remove_environmentalmechanism_overdue_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='environmentalmechanism',
            name='overdue_count',
            field=models.IntegerField(default=0),
        ),
    ]
