# Stub file for company.views

from django.http import HttpRequest, HttpResponse

def company_list(request: HttpRequest) -> HttpResponse: ...
def company_detail(request: HttpRequest, company_id: int) -> HttpResponse: ...
def company_create(request: HttpRequest) -> HttpResponse: ...
def company_edit(request: HttpRequest, company_id: int) -> HttpResponse: ...
def company_delete(request: HttpRequest, company_id: int) -> HttpResponse: ...
def manage_members(request: HttpRequest, company_id: int) -> HttpResponse: ...
def add_member(request: HttpRequest, company_id: int) -> HttpResponse: ...
def remove_member(
    request: HttpRequest, company_id: int, member_id: int
) -> HttpResponse: ...
def update_member_role(
    request: HttpRequest, company_id: int, member_id: int
) -> HttpResponse: ...
def upload_document(request: HttpRequest, company_id: int) -> HttpResponse: ...
def delete_document(
    request: HttpRequest, company_id: int, document_id: int
) -> HttpResponse: ...
