from _typeshed import Incomplete

register: Incomplete

@register.filter
def user_has_responsibility(user, obligation): ...
@register.filter
def user_responsibility_roles(user, obligation): ...
@register.filter
def format_responsibility_roles(roles): ...
@register.simple_tag
def get_responsible_users(obligation): ...
