// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.24.4

export enum MessageType {
  MESSAGE_TYPE_TEXT_UNSPECIFIED = 0,
  MESSAGE_TYPE_IMAGE = 1,
  MESSAGE_TYPE_AUDIO = 2,
}
