from datetime import date, datetime
from typing import Any

from _typeshed import Incomplete
from beartype import beartype as beartype

register: Incomplete
logger: Incomplete

@register.filter
def format_due_date(target_date: date | datetime | None) -> str: ...
@register.filter
def multiply(value: float, arg: float) -> float: ...
@register.filter
def display_status(obligation: Any) -> str: ...
@register.simple_tag
def status_badge(status: str) -> str: ...
@register.filter
def display_responsibility(responsibility: str | None) -> str: ...
@register.simple_tag
def get_active_obligations(active_obligations: Any = None) -> Any: ...
@register.simple_tag
def get_compliance_status(compliance_status: str | None = None) -> str: ...
@register.simple_tag
def get_next_due_obligation(next_due_obligation: Any = None) -> Any: ...
