// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.24.4

import { Writer, Reader } from "as-proto/assembly";

export class ChartSegment {
  static encode(message: ChartSegment, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.label);

    writer.uint32(16);
    writer.int32(message.value);

    writer.uint32(26);
    writer.string(message.color);
  }

  static decode(reader: Reader, length: i32): ChartSegment {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new ChartSegment();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.label = reader.string();
          break;

        case 2:
          message.value = reader.int32();
          break;

        case 3:
          message.color = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  label: string;
  value: i32;
  color: string;

  constructor(label: string = "", value: i32 = 0, color: string = "") {
    this.label = label;
    this.value = value;
    this.color = color;
  }
}
