// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.24.4

import { Writer, Reader } from "as-proto/assembly";
import { ChartData } from "./ChartData";

export class ChartResponse {
  static encode(message: ChartResponse, writer: Writer): void {
    const charts = message.charts;
    for (let i: i32 = 0; i < charts.length; ++i) {
      writer.uint32(10);
      writer.fork();
      ChartData.encode(charts[i], writer);
      writer.ldelim();
    }

    writer.uint32(18);
    writer.string(message.error);
  }

  static decode(reader: Reader, length: i32): ChartResponse {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new ChartResponse();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.charts.push(ChartData.decode(reader, reader.uint32()));
          break;

        case 2:
          message.error = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  charts: Array<ChartData>;
  error: string;

  constructor(charts: Array<ChartData> = [], error: string = "") {
    this.charts = charts;
    this.error = error;
  }
}
