// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.24.4

import { Writer, Reader } from "as-proto/assembly";
import { ChartSegment } from "./ChartSegment";

export class ChartData {
  static encode(message: ChartData, writer: Writer): void {
    const segments = message.segments;
    for (let i: i32 = 0; i < segments.length; ++i) {
      writer.uint32(10);
      writer.fork();
      ChartSegment.encode(segments[i], writer);
      writer.ldelim();
    }

    writer.uint32(16);
    writer.int32(message.mechanismId);

    writer.uint32(26);
    writer.string(message.mechanismName);
  }

  static decode(reader: Reader, length: i32): ChartData {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new ChartData();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.segments.push(ChartSegment.decode(reader, reader.uint32()));
          break;

        case 2:
          message.mechanismId = reader.int32();
          break;

        case 3:
          message.mechanismName = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  segments: Array<ChartSegment>;
  mechanismId: i32;
  mechanismName: string;

  constructor(
    segments: Array<ChartSegment> = [],
    mechanismId: i32 = 0,
    mechanismName: string = ""
  ) {
    this.segments = segments;
    this.mechanismId = mechanismId;
    this.mechanismName = mechanismName;
  }
}
