// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.24.4

export enum ObligationStatus {
  STATUS_UNKNOWN = 0,
  STATUS_NOT_STARTED = 1,
  STATUS_IN_PROGRESS = 2,
  STATUS_COMPLETED = 3,
  STATUS_OVERDUE = 4,
}
