// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.24.4

import { Writer, Reader } from "as-proto/assembly";
import { ObligationInsight } from "./ObligationInsight";

export class ObligationInsightResponse {
  static encode(message: ObligationInsightResponse, writer: Writer): void {
    writer.uint32(8);
    writer.int32(message.mechanismId);

    writer.uint32(18);
    writer.string(message.status);

    writer.uint32(26);
    writer.string(message.statusKey);

    writer.uint32(32);
    writer.int32(message.count);

    writer.uint32(40);
    writer.int32(message.totalCount);

    const obligations = message.obligations;
    for (let i: i32 = 0; i < obligations.length; ++i) {
      writer.uint32(50);
      writer.fork();
      ObligationInsight.encode(obligations[i], writer);
      writer.ldelim();
    }

    writer.uint32(58);
    writer.string(message.error);
  }

  static decode(reader: Reader, length: i32): ObligationInsightResponse {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new ObligationInsightResponse();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.mechanismId = reader.int32();
          break;

        case 2:
          message.status = reader.string();
          break;

        case 3:
          message.statusKey = reader.string();
          break;

        case 4:
          message.count = reader.int32();
          break;

        case 5:
          message.totalCount = reader.int32();
          break;

        case 6:
          message.obligations.push(
            ObligationInsight.decode(reader, reader.uint32())
          );
          break;

        case 7:
          message.error = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  mechanismId: i32;
  status: string;
  statusKey: string;
  count: i32;
  totalCount: i32;
  obligations: Array<ObligationInsight>;
  error: string;

  constructor(
    mechanismId: i32 = 0,
    status: string = "",
    statusKey: string = "",
    count: i32 = 0,
    totalCount: i32 = 0,
    obligations: Array<ObligationInsight> = [],
    error: string = ""
  ) {
    this.mechanismId = mechanismId;
    this.status = status;
    this.statusKey = statusKey;
    this.count = count;
    this.totalCount = totalCount;
    this.obligations = obligations;
    this.error = error;
  }
}
