// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.24.4

import { Writer, Reader } from "as-proto/assembly";

export class ObligationInsight {
  static encode(message: ObligationInsight, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.obligationNumber);

    writer.uint32(18);
    writer.string(message.dueDate);

    writer.uint32(26);
    writer.string(message.closeOutDate);
  }

  static decode(reader: Reader, length: i32): ObligationInsight {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new ObligationInsight();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.obligationNumber = reader.string();
          break;

        case 2:
          message.dueDate = reader.string();
          break;

        case 3:
          message.closeOutDate = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  obligationNumber: string;
  dueDate: string;
  closeOutDate: string;

  constructor(
    obligationNumber: string = "",
    dueDate: string = "",
    closeOutDate: string = ""
  ) {
    this.obligationNumber = obligationNumber;
    this.dueDate = dueDate;
    this.closeOutDate = closeOutDate;
  }
}
