// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.24.4

import { Writer, Reader } from "as-proto/assembly";
import { AuditEntryProto } from "./AuditEntryProto";

export class AuditEntryCollection {
  static encode(message: AuditEntryCollection, writer: Writer): void {
    const auditEntries = message.auditEntries;
    for (let i: i32 = 0; i < auditEntries.length; ++i) {
      writer.uint32(10);
      writer.fork();
      AuditEntryProto.encode(auditEntries[i], writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): AuditEntryCollection {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new AuditEntryCollection();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.auditEntries.push(
            AuditEntryProto.decode(reader, reader.uint32())
          );
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  auditEntries: Array<AuditEntryProto>;

  constructor(auditEntries: Array<AuditEntryProto> = []) {
    this.auditEntries = auditEntries;
  }
}
