// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.24.4

import { Writer, Reader } from "as-proto/assembly";
import { AuditProto } from "./AuditProto";

export class AuditCollection {
  static encode(message: AuditCollection, writer: Writer): void {
    const audits = message.audits;
    for (let i: i32 = 0; i < audits.length; ++i) {
      writer.uint32(10);
      writer.fork();
      AuditProto.encode(audits[i], writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): AuditCollection {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new AuditCollection();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.audits.push(AuditProto.decode(reader, reader.uint32()));
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  audits: Array<AuditProto>;

  constructor(audits: Array<AuditProto> = []) {
    this.audits = audits;
  }
}
