// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.24.4

import { Writer, Reader } from "as-proto/assembly";

export class AuditProto {
  static encode(message: AuditProto, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.id);

    writer.uint32(18);
    writer.string(message.name);

    writer.uint32(26);
    writer.string(message.createdAt);

    const mechanismIds = message.mechanismIds;
    if (mechanismIds.length !== 0) {
      for (let i: i32 = 0; i < mechanismIds.length; ++i) {
        writer.uint32(34);
        writer.string(mechanismIds[i]);
      }
    }
  }

  static decode(reader: Reader, length: i32): AuditProto {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new AuditProto();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.id = reader.string();
          break;

        case 2:
          message.name = reader.string();
          break;

        case 3:
          message.createdAt = reader.string();
          break;

        case 4:
          message.mechanismIds.push(reader.string());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  id: string;
  name: string;
  createdAt: string;
  mechanismIds: Array<string>;

  constructor(
    id: string = "",
    name: string = "",
    createdAt: string = "",
    mechanismIds: Array<string> = []
  ) {
    this.id = id;
    this.name = name;
    this.createdAt = createdAt;
    this.mechanismIds = mechanismIds;
  }
}
