// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.24.4

import { Writer, Reader } from "as-proto/assembly";

export class AuditEntryProto {
  static encode(message: AuditEntryProto, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.id);

    writer.uint32(18);
    writer.string(message.auditId);

    writer.uint32(26);
    writer.string(message.obligationId);

    writer.uint32(34);
    writer.string(message.status);

    writer.uint32(42);
    writer.string(message.finding);
  }

  static decode(reader: Reader, length: i32): AuditEntryProto {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new AuditEntryProto();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.id = reader.string();
          break;

        case 2:
          message.auditId = reader.string();
          break;

        case 3:
          message.obligationId = reader.string();
          break;

        case 4:
          message.status = reader.string();
          break;

        case 5:
          message.finding = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  id: string;
  auditId: string;
  obligationId: string;
  status: string;
  finding: string;

  constructor(
    id: string = "",
    auditId: string = "",
    obligationId: string = "",
    status: string = "",
    finding: string = ""
  ) {
    this.id = id;
    this.auditId = auditId;
    this.obligationId = obligationId;
    this.status = status;
    this.finding = finding;
  }
}
