// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.24.4

import { Writer, Reader } from "as-proto/assembly";
import { ComplianceCommentProto } from "./ComplianceCommentProto";

export class ComplianceCommentCollection {
  static encode(message: ComplianceCommentCollection, writer: Writer): void {
    const complianceComments = message.complianceComments;
    for (let i: i32 = 0; i < complianceComments.length; ++i) {
      writer.uint32(10);
      writer.fork();
      ComplianceCommentProto.encode(complianceComments[i], writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): ComplianceCommentCollection {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new ComplianceCommentCollection();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.complianceComments.push(
            ComplianceCommentProto.decode(reader, reader.uint32())
          );
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  complianceComments: Array<ComplianceCommentProto>;

  constructor(complianceComments: Array<ComplianceCommentProto> = []) {
    this.complianceComments = complianceComments;
  }
}
