// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.24.4

import { Writer, Reader } from "as-proto/assembly";

export class ComplianceCommentProto {
  static encode(message: ComplianceCommentProto, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.id);

    writer.uint32(18);
    writer.string(message.obligationId);

    writer.uint32(26);
    writer.string(message.text);

    writer.uint32(34);
    writer.string(message.createdAt);
  }

  static decode(reader: Reader, length: i32): ComplianceCommentProto {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new ComplianceCommentProto();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.id = reader.string();
          break;

        case 2:
          message.obligationId = reader.string();
          break;

        case 3:
          message.text = reader.string();
          break;

        case 4:
          message.createdAt = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  id: string;
  obligationId: string;
  text: string;
  createdAt: string;

  constructor(
    id: string = "",
    obligationId: string = "",
    text: string = "",
    createdAt: string = ""
  ) {
    this.id = id;
    this.obligationId = obligationId;
    this.text = text;
    this.createdAt = createdAt;
  }
}
