// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.24.4

import { Writer, Reader } from "as-proto/assembly";
import { CorrectiveActionProto } from "./CorrectiveActionProto";

export class CorrectiveActionCollection {
  static encode(message: CorrectiveActionCollection, writer: Writer): void {
    const correctiveActions = message.correctiveActions;
    for (let i: i32 = 0; i < correctiveActions.length; ++i) {
      writer.uint32(10);
      writer.fork();
      CorrectiveActionProto.encode(correctiveActions[i], writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): CorrectiveActionCollection {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new CorrectiveActionCollection();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.correctiveActions.push(
            CorrectiveActionProto.decode(reader, reader.uint32())
          );
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  correctiveActions: Array<CorrectiveActionProto>;

  constructor(correctiveActions: Array<CorrectiveActionProto> = []) {
    this.correctiveActions = correctiveActions;
  }
}
