// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.24.4

import { Writer, Reader } from "as-proto/assembly";

export class CorrectiveActionProto {
  static encode(message: CorrectiveActionProto, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.id);

    writer.uint32(18);
    writer.string(message.mitigationId);

    writer.uint32(26);
    writer.string(message.task);

    writer.uint32(34);
    writer.string(message.status);

    writer.uint32(42);
    writer.string(message.assignedToUserId);

    writer.uint32(50);
    writer.string(message.createdAt);

    writer.uint32(58);
    writer.string(message.dueDate);
  }

  static decode(reader: Reader, length: i32): CorrectiveActionProto {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new CorrectiveActionProto();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.id = reader.string();
          break;

        case 2:
          message.mitigationId = reader.string();
          break;

        case 3:
          message.task = reader.string();
          break;

        case 4:
          message.status = reader.string();
          break;

        case 5:
          message.assignedToUserId = reader.string();
          break;

        case 6:
          message.createdAt = reader.string();
          break;

        case 7:
          message.dueDate = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  id: string;
  mitigationId: string;
  task: string;
  status: string;
  assignedToUserId: string;
  createdAt: string;
  dueDate: string;

  constructor(
    id: string = "",
    mitigationId: string = "",
    task: string = "",
    status: string = "",
    assignedToUserId: string = "",
    createdAt: string = "",
    dueDate: string = ""
  ) {
    this.id = id;
    this.mitigationId = mitigationId;
    this.task = task;
    this.status = status;
    this.assignedToUserId = assignedToUserId;
    this.createdAt = createdAt;
    this.dueDate = dueDate;
  }
}
