// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.24.4

import { Writer, Reader } from "as-proto/assembly";
import { MitigationProto } from "./MitigationProto";

export class MitigationCollection {
  static encode(message: MitigationCollection, writer: Writer): void {
    const mitigations = message.mitigations;
    for (let i: i32 = 0; i < mitigations.length; ++i) {
      writer.uint32(10);
      writer.fork();
      MitigationProto.encode(mitigations[i], writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): MitigationCollection {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new MitigationCollection();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.mitigations.push(
            MitigationProto.decode(reader, reader.uint32())
          );
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  mitigations: Array<MitigationProto>;

  constructor(mitigations: Array<MitigationProto> = []) {
    this.mitigations = mitigations;
  }
}
