// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.24.4

import { Writer, Reader } from "as-proto/assembly";

export class MitigationProto {
  static encode(message: MitigationProto, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.id);

    writer.uint32(18);
    writer.string(message.auditEntryId);

    writer.uint32(26);
    writer.string(message.description);

    writer.uint32(34);
    writer.string(message.status);

    writer.uint32(42);
    writer.string(message.createdAt);
  }

  static decode(reader: Reader, length: i32): MitigationProto {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new MitigationProto();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.id = reader.string();
          break;

        case 2:
          message.auditEntryId = reader.string();
          break;

        case 3:
          message.description = reader.string();
          break;

        case 4:
          message.status = reader.string();
          break;

        case 5:
          message.createdAt = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  id: string;
  auditEntryId: string;
  description: string;
  status: string;
  createdAt: string;

  constructor(
    id: string = "",
    auditEntryId: string = "",
    description: string = "",
    status: string = "",
    createdAt: string = ""
  ) {
    this.id = id;
    this.auditEntryId = auditEntryId;
    this.description = description;
    this.status = status;
    this.createdAt = createdAt;
  }
}
