// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.24.4

import { Writer, Reader } from "as-proto/assembly";
import { NonConformanceCommentProto } from "./NonConformanceCommentProto";

export class NonConformanceCommentCollection {
  static encode(
    message: NonConformanceCommentCollection,
    writer: Writer
  ): void {
    const nonConformanceComments = message.nonConformanceComments;
    for (let i: i32 = 0; i < nonConformanceComments.length; ++i) {
      writer.uint32(10);
      writer.fork();
      NonConformanceCommentProto.encode(nonConformanceComments[i], writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): NonConformanceCommentCollection {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new NonConformanceCommentCollection();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.nonConformanceComments.push(
            NonConformanceCommentProto.decode(reader, reader.uint32())
          );
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  nonConformanceComments: Array<NonConformanceCommentProto>;

  constructor(nonConformanceComments: Array<NonConformanceCommentProto> = []) {
    this.nonConformanceComments = nonConformanceComments;
  }
}
