// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.24.4

import { Writer, Reader } from "as-proto/assembly";
import { BugReportProto } from "./BugReportProto";

export class BugReportCollection {
  static encode(message: BugReportCollection, writer: Writer): void {
    const reports = message.reports;
    for (let i: i32 = 0; i < reports.length; ++i) {
      writer.uint32(10);
      writer.fork();
      BugReportProto.encode(reports[i], writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): BugReportCollection {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new BugReportCollection();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.reports.push(BugReportProto.decode(reader, reader.uint32()));
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  reports: Array<BugReportProto>;

  constructor(reports: Array<BugReportProto> = []) {
    this.reports = reports;
  }
}
