// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.24.4

import { Writer, Reader } from "as-proto/assembly";
import { Frequency } from "./BugReportProto/Frequency";
import { Severity } from "./BugReportProto/Severity";
import { Status } from "./BugReportProto/Status";

export class BugReportProto {
  static encode(message: BugReportProto, writer: Writer): void {
    writer.uint32(8);
    writer.int32(message.id);

    writer.uint32(18);
    writer.string(message.title);

    writer.uint32(26);
    writer.string(message.description);

    writer.uint32(34);
    writer.string(message.applicationVersion);

    writer.uint32(42);
    writer.string(message.operatingSystem);

    writer.uint32(50);
    writer.string(message.browser);

    writer.uint32(58);
    writer.string(message.deviceType);

    writer.uint32(66);
    writer.string(message.stepsToReproduce);

    writer.uint32(74);
    writer.string(message.expectedBehavior);

    writer.uint32(82);
    writer.string(message.actualBehavior);

    writer.uint32(90);
    writer.string(message.errorMessages);

    writer.uint32(98);
    writer.string(message.traceReport);

    writer.uint32(104);
    writer.int32(message.frequency);

    writer.uint32(112);
    writer.int32(message.impactSeverity);

    writer.uint32(120);
    writer.int32(message.adminSeverity);

    writer.uint32(130);
    writer.string(message.userImpact);

    writer.uint32(138);
    writer.string(message.workarounds);

    writer.uint32(146);
    writer.string(message.additionalComments);

    writer.uint32(152);
    writer.int32(message.userId);

    writer.uint32(162);
    writer.string(message.username);

    writer.uint32(168);
    writer.int64(message.createdAt);

    writer.uint32(176);
    writer.int64(message.updatedAt);

    writer.uint32(186);
    writer.string(message.githubIssueUrl);

    writer.uint32(192);
    writer.int32(message.status);

    writer.uint32(202);
    writer.string(message.adminComment);
  }

  static decode(reader: Reader, length: i32): BugReportProto {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new BugReportProto();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.id = reader.int32();
          break;

        case 2:
          message.title = reader.string();
          break;

        case 3:
          message.description = reader.string();
          break;

        case 4:
          message.applicationVersion = reader.string();
          break;

        case 5:
          message.operatingSystem = reader.string();
          break;

        case 6:
          message.browser = reader.string();
          break;

        case 7:
          message.deviceType = reader.string();
          break;

        case 8:
          message.stepsToReproduce = reader.string();
          break;

        case 9:
          message.expectedBehavior = reader.string();
          break;

        case 10:
          message.actualBehavior = reader.string();
          break;

        case 11:
          message.errorMessages = reader.string();
          break;

        case 12:
          message.traceReport = reader.string();
          break;

        case 13:
          message.frequency = reader.int32();
          break;

        case 14:
          message.impactSeverity = reader.int32();
          break;

        case 15:
          message.adminSeverity = reader.int32();
          break;

        case 16:
          message.userImpact = reader.string();
          break;

        case 17:
          message.workarounds = reader.string();
          break;

        case 18:
          message.additionalComments = reader.string();
          break;

        case 19:
          message.userId = reader.int32();
          break;

        case 20:
          message.username = reader.string();
          break;

        case 21:
          message.createdAt = reader.int64();
          break;

        case 22:
          message.updatedAt = reader.int64();
          break;

        case 23:
          message.githubIssueUrl = reader.string();
          break;

        case 24:
          message.status = reader.int32();
          break;

        case 25:
          message.adminComment = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  id: i32;
  title: string;
  description: string;
  applicationVersion: string;
  operatingSystem: string;
  browser: string;
  deviceType: string;
  stepsToReproduce: string;
  expectedBehavior: string;
  actualBehavior: string;
  errorMessages: string;
  traceReport: string;
  frequency: Frequency;
  impactSeverity: Severity;
  adminSeverity: Severity;
  userImpact: string;
  workarounds: string;
  additionalComments: string;
  userId: i32;
  username: string;
  createdAt: i64;
  updatedAt: i64;
  githubIssueUrl: string;
  status: Status;
  adminComment: string;

  constructor(
    id: i32 = 0,
    title: string = "",
    description: string = "",
    applicationVersion: string = "",
    operatingSystem: string = "",
    browser: string = "",
    deviceType: string = "",
    stepsToReproduce: string = "",
    expectedBehavior: string = "",
    actualBehavior: string = "",
    errorMessages: string = "",
    traceReport: string = "",
    frequency: Frequency = 0,
    impactSeverity: Severity = 0,
    adminSeverity: Severity = 0,
    userImpact: string = "",
    workarounds: string = "",
    additionalComments: string = "",
    userId: i32 = 0,
    username: string = "",
    createdAt: i64 = 0,
    updatedAt: i64 = 0,
    githubIssueUrl: string = "",
    status: Status = 0,
    adminComment: string = ""
  ) {
    this.id = id;
    this.title = title;
    this.description = description;
    this.applicationVersion = applicationVersion;
    this.operatingSystem = operatingSystem;
    this.browser = browser;
    this.deviceType = deviceType;
    this.stepsToReproduce = stepsToReproduce;
    this.expectedBehavior = expectedBehavior;
    this.actualBehavior = actualBehavior;
    this.errorMessages = errorMessages;
    this.traceReport = traceReport;
    this.frequency = frequency;
    this.impactSeverity = impactSeverity;
    this.adminSeverity = adminSeverity;
    this.userImpact = userImpact;
    this.workarounds = workarounds;
    this.additionalComments = additionalComments;
    this.userId = userId;
    this.username = username;
    this.createdAt = createdAt;
    this.updatedAt = updatedAt;
    this.githubIssueUrl = githubIssueUrl;
    this.status = status;
    this.adminComment = adminComment;
  }
}
