MAIN_NAVIGATION: list[tuple[str, str, str]]
USER_NAVIGATION: list[tuple[str, str, str]]
AUTH_NAVIGATION: list[tuple[str, str, str]]
THEME_OPTIONS: list[tuple[str, str]]
FOOTER_LINKS: list[tuple[str, str, bool]]
