from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.base import ContextMixin
from typing import Any, TypeVar

ContextView = TypeVar('ContextView', bound=ContextMixin)

class BreadcrumbMixin(ContextMixin):
    breadcrumbs: list[tuple[str, str | None]]
    def get_breadcrumbs(self) -> list[tuple[str, str | None]]: ...
    def get_context_data(self, **kwargs) -> dict[str, Any]: ...

class PageTitleMixin(ContextMixin):
    page_title: str | None
    def get_page_title(self) -> str | None: ...
    def get_context_data(self, **kwargs) -> dict[str, Any]: ...

class SectionMixin(ContextMixin):
    active_section: str | None
    def get_active_section(self) -> str | None: ...
    def get_context_data(self, **kwargs) -> dict[str, Any]: ...

class ViewMixin(BreadcrumbMixin, PageTitleMixin, SectionMixin): ...
class AuthViewMixin(LoginRequiredMixin, ViewMixin): ...
