from ..models import Project
from _typeshed import Incomplete
from django.contrib.auth.models import AbstractUser
from django.db.models import QuerySet
from obligations.models import Obligation
from typing import Any

logger: Incomplete
register: Incomplete

def obligation_table(obligations: QuerySet[Obligation]) -> dict[str, Any]: ...
@register.filter
def get_item(dictionary: dict[str, Any], key: Any) -> Any: ...
@register.filter
def get_user_role(project: Project, user: AbstractUser) -> str: ...
@register.filter
def format_role(role: str) -> str: ...
def role_badge(role: str) -> dict[str, str]: ...
@register.filter
def transform_queryset(queryset, method_name): ...
@register.filter
def to_list(value): ...
@register.simple_tag
def project_status_badge(status: str) -> str: ...
@register.simple_tag
def project_badge(project_type: str, display_text: str | None = None) -> str: ...
def get_badge_config(project_type: str) -> dict[str, str]: ...
def project_list(projects: list[Any], max_items: int = 5) -> dict[str, Any]: ...
