# ...existing code...

INSTALLED_APPS = [
    # ...existing apps...
    'pb_model',  # Add this for protobuf support
    'chatbot',   # Add this for the chatbot app
    # ...other apps...
]

# ...existing code...
