from ..models import EnvironmentalMechanism
from _typeshed import Incomplete
from django.db.models import QuerySet
from typing import Any

register: Incomplete

@register.filter
def get_item(dictionary: dict[str, Any], key: Any) -> Any: ...
@register.filter
def mechanism_name(mechanism_id: int) -> str: ...
@register.filter
def format_count(count: int) -> str: ...
@register.filter
def total_obligations(mechanism: EnvironmentalMechanism) -> int: ...
def mechanism_card(mechanism: EnvironmentalMechanism) -> dict[str, Any]: ...
def mechanism_table(mechanisms: QuerySet[EnvironmentalMechanism]) -> dict[str, Any]: ...
@register.filter
def get_status_color(status: str) -> str: ...
