from beartype import beartype
from pathlib import Path

@beartype
def get_proto_dir() -> Path: ...
@beartype
def get_proto_files() -> list[Path]: ...
@beartype
def compile_proto_file(proto_file: Path, output_dir: Path | None = None) -> bool: ...
@beartype
def compile_all_protos() -> bool: ...
@beartype
def check_protoc_available() -> bool: ...
