# Generated by Django 5.1.6 on 2025-02-27 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectmembership",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "Owner"),
                    ("manager", "Manager"),
                    ("member", "Member"),
                    ("viewer", "Viewer"),
                    ("simon", "Simon"),
                ],
                default="member",
                max_length=20,
            ),
        ),
    ]
