# Generated by Django 5.1.6 on 2025-02-24 06:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("obligations", "0001_initial"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name="ProjectObligation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "obligation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_obligations",
                        to="obligations.obligation",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_obligations",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Obligation",
                "verbose_name_plural": "Project Obligations",
                "ordering": ["project", "obligation"],
                "unique_together": {("project", "obligation")},
            },
        ),
    ]
