# Generated by Django 5.1.6 on 2025-02-12 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "projects",
            "0002_obligation_action_due_date_obligation_close_out_date_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="obligation",
            options={
                "ordering": ["obligation_number"],
                "verbose_name": "Obligation",
                "verbose_name_plural": "Obligations",
            },
        ),
        migrations.AlterModelOptions(
            name="project",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
            },
        ),
    ]
