# Generated by Django 5.1.6 on 2025-02-18 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_alter_project_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Obligation",
        ),
    ]
