# Generated by Django 5.1.6 on 2025-02-20 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0010_alter_projectmembership_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projectmembership",
            options={
                "verbose_name": "Project Membership",
                "verbose_name_plural": "Project Memberships",
            },
        ),
        migrations.RemoveIndex(
            model_name="projectmembership",
            name="projects_pr_user_id_426451_idx",
        ),
        migrations.AlterField(
            model_name="projectmembership",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "Owner"),
                    ("manager", "Manager"),
                    ("member", "Member"),
                    ("viewer", "Viewer"),
                ],
                default="member",
                max_length=20,
            ),
        ),
    ]
