from _typeshed import Incomplete

register: Incomplete

@register.filter
def company_role(user, company): ...
@register.filter
def company_role_badge(role): ...
@register.filter
def company_type_label(company_type): ...
@register.filter
def industry_label(industry_code): ...
@register.simple_tag
def company_selector(user): ...
