import matplotlib.pyplot as plt
from _typeshed import Incomplete

logger: Incomplete

def create_obligations_status_chart(project_id: int | None = None) -> tuple[plt.Figure, bytes]: ...
def create_obligations_status_chart_svg(project_id: Incomplete | None = None): ...
def create_timeline_chart(project_id: int | None = None) -> tuple[plt.Figure, bytes]: ...
def create_project_compliance_chart(projects) -> tuple[plt.Figure, bytes]: ...
