from _typeshed import Incomplete
from collections.abc import Callable as Callable
from django.http import HttpRequest, HttpResponse

logger: Incomplete

class DashboardPersistenceMiddleware:
    get_response: Incomplete
    def __init__(self, get_response: Callable[[HttpRequest], HttpResponse]) -> None: ...
    def __call__(self, request: HttpRequest) -> HttpResponse: ...
    def process_request(self, request: HttpRequest) -> None: ...
    def process_response(self, request: HttpRequest, response: HttpResponse) -> None: ...
    def _is_dashboard_view(self, request: HttpRequest) -> bool: ...
