from _typeshed import Incomplete
from core.mixins import BreadcrumbMixin, PageTitleMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from typing import Any

logger: Incomplete

class ChartMixin: ...
class ProjectAwareDashboardMixin: ...

class DashboardContextMixin(LoginRequiredMixin, BreadcrumbMixin, PageTitleMixin):
    page_title: str
    breadcrumbs: Incomplete
    def get_context_data(self, **kwargs) -> dict[str, Any]: ...
    def _get_current_project_id(self) -> int | None: ...
    def _get_user_projects(self): ...
    def _add_chart_data(self, context: dict[str, Any], project_id: int | None) -> None: ...
    def _add_statistics(self, context: dict[str, Any], project_id: int | None) -> None: ...
