# Generated by Django 5.1.6 on 2025-02-24 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("mechanisms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Obligation",
            fields=[
                (
                    "obligation_number",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("procedure", models.TextField(blank=True, null=True)),
                ("environmental_aspect", models.CharField(max_length=255)),
                ("obligation", models.TextField()),
                ("accountability", models.CharField(max_length=255)),
                ("responsibility", models.CharField(max_length=255)),
                (
                    "project_phase",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("action_due_date", models.DateField(blank=True, null=True)),
                ("close_out_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not started", "Not Started"),
                            ("in progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        default="not started",
                        max_length=20,
                    ),
                ),
                ("supporting_information", models.TextField(blank=True, null=True)),
                ("general_comments", models.TextField(blank=True, null=True)),
                ("compliance_comments", models.TextField(blank=True, null=True)),
                ("non_conformance_comments", models.TextField(blank=True, null=True)),
                ("evidence", models.TextField(blank=True, null=True)),
                (
                    "person_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("recurring_obligation", models.BooleanField(default=False)),
                (
                    "recurring_frequency",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "recurring_status",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("recurring_forcasted_date", models.DateField(blank=True, null=True)),
                ("inspection", models.BooleanField(default=False)),
                (
                    "inspection_frequency",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "site_or_desktop",
                    models.CharField(
                        blank=True,
                        choices=[("Site", "Site"), ("Desktop", "Desktop")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("new_control_action_required", models.BooleanField(default=False)),
                (
                    "obligation_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("gap_analysis", models.TextField(blank=True, null=True)),
                ("notes_for_gap_analysis", models.TextField(blank=True, null=True)),
                (
                    "covered_in_which_inspection_checklist",
                    models.CharField(
                        blank=True,
                        help_text="Specifies which inspection checklist covers this obligation",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "primary_environmental_mechanism",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="obligations",
                        to="mechanisms.environmentalmechanism",
                    ),
                ),
            ],
            options={
                "verbose_name": "Obligation",
                "verbose_name_plural": "Obligations",
                "ordering": ["action_due_date", "obligation_number"],
            },
        ),
    ]
