# Generated by Django 5.1.5 on 2025-02-07 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Obligation",
            fields=[
                (
                    "obligation_number",
                    models.CharField(
                        help_text="Unique identifier for the obligation (e.g., PCEMP-01)",
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("project_name", models.CharField(max_length=255)),
                (
                    "primary_environmental_mechanism",
                    models.TextField(blank=True, null=True),
                ),
                ("procedure", models.TextField(blank=True, null=True)),
                ("environmental_aspect", models.TextField(blank=True, null=True)),
                ("obligation", models.TextField()),
                (
                    "accountability",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "responsibility",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("project_phase", models.TextField(blank=True, null=True)),
                (
                    "person_email",
                    models.EmailField(blank=True, max_length=255, null=True),
                ),
                ("action_due_date", models.DateField(blank=True, null=True)),
                ("close_out_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not started", "Not Started"),
                            ("in progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        default="not started",
                        max_length=50,
                    ),
                ),
                ("supporting_information", models.TextField(blank=True, null=True)),
                ("general_comments", models.TextField(blank=True, null=True)),
                ("compliance_comments", models.TextField(blank=True, null=True)),
                ("non_conformance_comments", models.TextField(blank=True, null=True)),
                ("evidence", models.TextField(blank=True, null=True)),
                ("recurring_obligation", models.BooleanField(default=False)),
                (
                    "recurring_frequency",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "recurring_status",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("recurring_forcasted_date", models.DateField(blank=True, null=True)),
                ("inspection", models.BooleanField(default=False)),
                (
                    "inspection_frequency",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "site_or_desktop",
                    models.CharField(
                        blank=True,
                        choices=[("Site", "Site"), ("Desktop", "Desktop")],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("new_control_action_required", models.BooleanField(default=False)),
                (
                    "obligation_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("gap_analysis", models.TextField(blank=True, null=True)),
                ("notes_for_gap_analysis", models.TextField(blank=True, null=True)),
                (
                    "covered_in_which_inspection_checklist",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_obligations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_obligations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Obligation",
                "verbose_name_plural": "Obligations",
                "ordering": ["obligation_number"],
                "indexes": [
                    models.Index(
                        fields=["project_name"], name="obligations_project_75a0d3_idx"
                    ),
                    models.Index(
                        fields=["status"], name="obligations_status_775e6e_idx"
                    ),
                    models.Index(
                        fields=["action_due_date"],
                        name="obligations_action__2c0b8f_idx",
                    ),
                    models.Index(
                        fields=["project_phase"], name="obligations_project_c80467_idx"
                    ),
                ],
            },
        ),
    ]
