# Generated by Django 5.1.6 on 2025-02-18 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("obligations", "0001_initial"),
        ("projects", "0009_project_members"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="obligation",
            options={
                "ordering": ["action_due_date", "obligation_number"],
                "verbose_name": "Obligation",
                "verbose_name_plural": "Obligations",
            },
        ),
        migrations.RemoveIndex(
            model_name="obligation",
            name="obligations_project_039c2c_idx",
        ),
        migrations.RemoveIndex(
            model_name="obligation",
            name="obligations_primary_c912a0_idx",
        ),
        migrations.RemoveField(
            model_name="obligation",
            name="covered_in_which_inspection_checklist",
        ),
        migrations.AddIndex(
            model_name="obligation",
            index=models.Index(fields=["status"], name="obligations_status_775e6e_idx"),
        ),
        migrations.AddIndex(
            model_name="obligation",
            index=models.Index(
                fields=["project"], name="obligations_project_de2c9f_idx"
            ),
        ),
    ]
