# Generated by Django 5.1.6 on 2025-02-24 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("obligations", "0001_initial"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="obligation",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="obligations",
                to="projects.project",
            ),
        ),
        migrations.AddIndex(
            model_name="obligation",
            index=models.Index(fields=["status"], name="obligations_status_775e6e_idx"),
        ),
        migrations.AddIndex(
            model_name="obligation",
            index=models.Index(
                fields=["action_due_date"], name="obligations_action__2c0b8f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="obligation",
            index=models.Index(
                fields=["project"], name="obligations_project_de2c9f_idx"
            ),
        ),
    ]
