# Generated by Django 5.1.5 on 2025-02-10 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("obligations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="obligation",
            name="status",
            field=models.CharField(
                choices=[
                    ("not started", "Not Started"),
                    ("in progress", "In Progress"),
                    ("completed", "Completed"),
                    ("overdue", "Overdue"),
                ],
                default="not started",
                max_length=50,
            ),
        ),
    ]
