# Generated by Django 5.1.6 on 2025-02-27 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("obligations", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="obligation",
            name="obligation_number",
            field=models.CharField(
                help_text="Format: PCEMP-XXX where XXX is a number",
                max_length=20,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
