# Generated by Django 5.1.6 on 2025-02-19 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("obligations", "0002_alter_obligation_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="obligation",
            name="covered_in_which_inspection_checklist",
            field=models.CharField(
                blank=True,
                help_text="Specifies which inspection checklist covers this obligation",
                max_length=255,
                null=True,
            ),
        ),
    ]
