# Generated by Django 5.1.6 on 2025-02-27 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("obligations", "0003_alter_obligation_obligation_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="obligation",
            name="project_phase",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Pre-Construction", "Pre-Construction"),
                    ("Construction", "Construction"),
                    ("Operation", "Operation"),
                    ("Decommissioning", "Decommissioning"),
                    ("Post-Closure", "Post-Closure"),
                    ("Other", "Other"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
