# Generated by Django 5.1.6 on 2025-02-28 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obligations', '0005_alter_obligation_environmental_aspect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obligation',
            name='environmental_aspect',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='obligation',
            name='obligation_number',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='obligation',
            name='project_phase',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
