# Generated by Django 5.1.6 on 2025-02-28 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obligations', '0006_alter_obligation_environmental_aspect_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obligation',
            name='environmental_aspect',
            field=models.CharField(choices=[('Air', 'Air'), ('Water', 'Water'), ('Waste', 'Waste'), ('Energy', 'Energy'), ('Biodiversity', 'Biodiversity'), ('Noise', 'Noise'), ('Chemicals', 'Chemicals'), ('Soil', 'Soil'), ('Other', 'Other')], max_length=255),
        ),
        migrations.AlterField(
            model_name='obligation',
            name='obligation_number',
            field=models.CharField(help_text='Format: PCEMP-XXX where XXX is a number', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='obligation',
            name='project_phase',
            field=models.CharField(blank=True, choices=[('Pre-Construction', 'Pre-Construction'), ('Construction', 'Construction'), ('Operation', 'Operation'), ('Decommissioning', 'Decommissioning'), ('Post-Closure', 'Post-Closure'), ('Other', 'Other')], max_length=255, null=True),
        ),
    ]
