// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.24.4

import { Writer, Reader } from "as-proto/assembly";
import { DashboardWidget } from "./DashboardWidget";

export class DashboardLayout {
  static encode(message: DashboardLayout, writer: Writer): void {
    const widgets = message.widgets;
    for (let i: i32 = 0; i < widgets.length; ++i) {
      writer.uint32(10);
      writer.fork();
      DashboardWidget.encode(widgets[i], writer);
      writer.ldelim();
    }

    writer.uint32(18);
    writer.string(message.layoutJson);
  }

  static decode(reader: Reader, length: i32): DashboardLayout {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new DashboardLayout();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.widgets.push(DashboardWidget.decode(reader, reader.uint32()));
          break;

        case 2:
          message.layoutJson = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  widgets: Array<DashboardWidget>;
  layoutJson: string;

  constructor(widgets: Array<DashboardWidget> = [], layoutJson: string = "") {
    this.widgets = widgets;
    this.layoutJson = layoutJson;
  }
}
