// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.24.4

import { Writer, Reader } from "as-proto/assembly";

export class DashboardWidget {
  static encode(message: DashboardWidget, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.id);

    writer.uint32(18);
    writer.string(message.name);

    writer.uint32(26);
    writer.string(message.type);

    writer.uint32(34);
    writer.string(message.configJson);
  }

  static decode(reader: Reader, length: i32): DashboardWidget {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new DashboardWidget();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.id = reader.string();
          break;

        case 2:
          message.name = reader.string();
          break;

        case 3:
          message.type = reader.string();
          break;

        case 4:
          message.configJson = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  id: string;
  name: string;
  type: string;
  configJson: string;

  constructor(
    id: string = "",
    name: string = "",
    type: string = "",
    configJson: string = ""
  ) {
    this.id = id;
    this.name = name;
    this.type = type;
    this.configJson = configJson;
  }
}
