// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.24.4

import { Writer, Reader } from "as-proto/assembly";
import { DashboardLayout } from "./DashboardLayout";
import { DashboardPreferences } from "./DashboardPreferences";

export class DashboardAPIResponse {
  static encode(message: DashboardAPIResponse, writer: Writer): void {
    const layout = message.layout;
    if (layout !== null) {
      writer.uint32(10);
      writer.fork();
      DashboardLayout.encode(layout, writer);
      writer.ldelim();
    }

    const preferences = message.preferences;
    if (preferences !== null) {
      writer.uint32(18);
      writer.fork();
      DashboardPreferences.encode(preferences, writer);
      writer.ldelim();
    }

    writer.uint32(24);
    writer.int64(message.lastUpdated);
  }

  static decode(reader: Reader, length: i32): DashboardAPIResponse {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new DashboardAPIResponse();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.layout = DashboardLayout.decode(reader, reader.uint32());
          break;

        case 2:
          message.preferences = DashboardPreferences.decode(
            reader,
            reader.uint32()
          );
          break;

        case 3:
          message.lastUpdated = reader.int64();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  layout: DashboardLayout | null;
  preferences: DashboardPreferences | null;
  lastUpdated: i64;

  constructor(
    layout: DashboardLayout | null = null,
    preferences: DashboardPreferences | null = null,
    lastUpdated: i64 = 0
  ) {
    this.layout = layout;
    this.preferences = preferences;
    this.lastUpdated = lastUpdated;
  }
}
