// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.24.4

import { Writer, Reader } from "as-proto/assembly";

export class DashboardPreferences {
  static encode(message: DashboardPreferences, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.userId);

    writer.uint32(18);
    writer.string(message.selectedProject);

    writer.uint32(26);
    writer.string(message.selectedMechanism);

    writer.uint32(34);
    writer.string(message.preferencesJson);
  }

  static decode(reader: Reader, length: i32): DashboardPreferences {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new DashboardPreferences();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.userId = reader.string();
          break;

        case 2:
          message.selectedProject = reader.string();
          break;

        case 3:
          message.selectedMechanism = reader.string();
          break;

        case 4:
          message.preferencesJson = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  userId: string;
  selectedProject: string;
  selectedMechanism: string;
  preferencesJson: string;

  constructor(
    userId: string = "",
    selectedProject: string = "",
    selectedMechanism: string = "",
    preferencesJson: string = ""
  ) {
    this.userId = userId;
    this.selectedProject = selectedProject;
    this.selectedMechanism = selectedMechanism;
    this.preferencesJson = preferencesJson;
  }
}
