// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.24.4

export enum Frequency {
  FREQUENCY_UNKNOWN_UNSPECIFIED = 0,
  FREQUENCY_ALWAYS = 1,
  FREQUENCY_FREQUENTLY = 2,
  FREQUENCY_OCCASIONALLY = 3,
  FREQUENCY_RARELY = 4,
}
