// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.24.4

export enum Status {
  STATUS_UNSPECIFIED = 0,
  STATUS_OPEN = 1,
  STATUS_IN_PROGRESS = 2,
  STATUS_RESOLVED = 3,
  STATUS_CLOSED = 4,
  STATUS_REJECTED = 5,
}
