# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: users.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0busers.proto\x12\x05users\"\x87\x01\n\tUserProto\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x12\n\nfirst_name\x18\x04 \x01(\t\x12\x11\n\tlast_name\x18\x05 \x01(\t\x12\x11\n\tis_active\x18\x06 \x01(\x08\x12\x13\n\x0b\x64\x61te_joined\x18\x07 \x01(\t\"\xb7\x01\n\x0cProfileProto\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x0b\n\x03\x62io\x18\x03 \x01(\t\x12\x10\n\x08position\x18\x04 \x01(\t\x12\x12\n\ndepartment\x18\x05 \x01(\t\x12\x14\n\x0cphone_number\x18\x06 \x01(\t\x12\x19\n\x11profile_image_url\x18\x07 \x01(\t\x12\x12\n\ncreated_at\x18\x08 \x01(\t\x12\x12\n\nupdated_at\x18\t \x01(\t\"1\n\x0eUserCollection\x12\x1f\n\x05users\x18\x01 \x03(\x0b\x32\x10.users.UserProto\":\n\x11ProfileCollection\x12%\n\x08profiles\x18\x01 \x03(\x0b\x32\x13.users.ProfileProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'users_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_USERPROTO']._serialized_start=23
  _globals['_USERPROTO']._serialized_end=158
  _globals['_PROFILEPROTO']._serialized_start=161
  _globals['_PROFILEPROTO']._serialized_end=344
  _globals['_USERCOLLECTION']._serialized_start=346
  _globals['_USERCOLLECTION']._serialized_end=395
  _globals['_PROFILECOLLECTION']._serialized_start=397
  _globals['_PROFILECOLLECTION']._serialized_end=455
# @@protoc_insertion_point(module_scope)
