
# Stub file for core.templatetags.core_tags

from django.template import Library

register: Library

def active_link(context: object, url_name: str, css_class: str = ...) -> str: ...
def breadcrumb_navigation(context: object) -> dict: ...
def auth_menu(context: object) -> dict: ...
def theme_switcher() -> dict: ...
def site_version() -> str: ...
def main_navigation(context: object) -> dict: ...
def user_role_in_project(project: object, user: object) -> object: ...
def base_url(context: object) -> str: ...
