// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.24.4

import { Writer, Reader } from "as-proto/assembly";

export class ProjectObligationProto {
  static encode(message: ProjectObligationProto, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.id);

    writer.uint32(18);
    writer.string(message.projectId);

    writer.uint32(26);
    writer.string(message.obligationId);

    writer.uint32(34);
    writer.string(message.createdAt);

    writer.uint32(42);
    writer.string(message.updatedAt);
  }

  static decode(reader: Reader, length: i32): ProjectObligationProto {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new ProjectObligationProto();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.id = reader.string();
          break;

        case 2:
          message.projectId = reader.string();
          break;

        case 3:
          message.obligationId = reader.string();
          break;

        case 4:
          message.createdAt = reader.string();
          break;

        case 5:
          message.updatedAt = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  id: string;
  projectId: string;
  obligationId: string;
  createdAt: string;
  updatedAt: string;

  constructor(
    id: string = "",
    projectId: string = "",
    obligationId: string = "",
    createdAt: string = "",
    updatedAt: string = ""
  ) {
    this.id = id;
    this.projectId = projectId;
    this.obligationId = obligationId;
    this.createdAt = createdAt;
    this.updatedAt = updatedAt;
  }
}
