// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.24.4

import { Writer, Reader } from "as-proto/assembly";
import { ProjectObligationProto } from "./ProjectObligationProto";

export class ProjectObligationCollection {
  static encode(message: ProjectObligationCollection, writer: Writer): void {
    const projectObligations = message.projectObligations;
    for (let i: i32 = 0; i < projectObligations.length; ++i) {
      writer.uint32(10);
      writer.fork();
      ProjectObligationProto.encode(projectObligations[i], writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): ProjectObligationCollection {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new ProjectObligationCollection();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.projectObligations.push(
            ProjectObligationProto.decode(reader, reader.uint32())
          );
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  projectObligations: Array<ProjectObligationProto>;

  constructor(projectObligations: Array<ProjectObligationProto> = []) {
    this.projectObligations = projectObligations;
  }
}
