// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.24.4

import { Writer, Reader } from "as-proto/assembly";
import { ProjectProto } from "./ProjectProto";

export class ProjectCollection {
  static encode(message: ProjectCollection, writer: Writer): void {
    const projects = message.projects;
    for (let i: i32 = 0; i < projects.length; ++i) {
      writer.uint32(10);
      writer.fork();
      ProjectProto.encode(projects[i], writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): ProjectCollection {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new ProjectCollection();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.projects.push(ProjectProto.decode(reader, reader.uint32()));
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  projects: Array<ProjectProto>;

  constructor(projects: Array<ProjectProto> = []) {
    this.projects = projects;
  }
}
