// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.24.4

import { Writer, Reader } from "as-proto/assembly";

export class ProjectProto {
  static encode(message: ProjectProto, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.id);

    writer.uint32(18);
    writer.string(message.name);

    writer.uint32(26);
    writer.string(message.description);

    const memberUserIds = message.memberUserIds;
    if (memberUserIds.length !== 0) {
      for (let i: i32 = 0; i < memberUserIds.length; ++i) {
        writer.uint32(34);
        writer.string(memberUserIds[i]);
      }
    }

    writer.uint32(42);
    writer.string(message.createdAt);

    writer.uint32(50);
    writer.string(message.updatedAt);
  }

  static decode(reader: Reader, length: i32): ProjectProto {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new ProjectProto();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.id = reader.string();
          break;

        case 2:
          message.name = reader.string();
          break;

        case 3:
          message.description = reader.string();
          break;

        case 4:
          message.memberUserIds.push(reader.string());
          break;

        case 5:
          message.createdAt = reader.string();
          break;

        case 6:
          message.updatedAt = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  id: string;
  name: string;
  description: string;
  memberUserIds: Array<string>;
  createdAt: string;
  updatedAt: string;

  constructor(
    id: string = "",
    name: string = "",
    description: string = "",
    memberUserIds: Array<string> = [],
    createdAt: string = "",
    updatedAt: string = ""
  ) {
    this.id = id;
    this.name = name;
    this.description = description;
    this.memberUserIds = memberUserIds;
    this.createdAt = createdAt;
    this.updatedAt = updatedAt;
  }
}
