// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.24.4

import { Writer, Reader } from "as-proto/assembly";
import { MessageType } from "./ChatMessage/MessageType";

export class ChatMessage {
  static encode(message: ChatMessage, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.userId);

    writer.uint32(18);
    writer.string(message.content);

    writer.uint32(24);
    writer.int64(message.timestamp);

    writer.uint32(32);
    writer.int32(message.type);
  }

  static decode(reader: Reader, length: i32): ChatMessage {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new ChatMessage();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.userId = reader.string();
          break;

        case 2:
          message.content = reader.string();
          break;

        case 3:
          message.timestamp = reader.int64();
          break;

        case 4:
          message.type = reader.int32();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  userId: string;
  content: string;
  timestamp: i64;
  type: MessageType;

  constructor(
    userId: string = "",
    content: string = "",
    timestamp: i64 = 0,
    type: MessageType = 0
  ) {
    this.userId = userId;
    this.content = content;
    this.timestamp = timestamp;
    this.type = type;
  }
}
