// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.24.4

import { Writer, Reader } from "as-proto/assembly";

export class ChatResponse {
  static encode(message: ChatResponse, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.messageId);

    writer.uint32(18);
    writer.string(message.content);

    writer.uint32(24);
    writer.int64(message.timestamp);
  }

  static decode(reader: Reader, length: i32): ChatResponse {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new ChatResponse();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.messageId = reader.string();
          break;

        case 2:
          message.content = reader.string();
          break;

        case 3:
          message.timestamp = reader.int64();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  messageId: string;
  content: string;
  timestamp: i64;

  constructor(
    messageId: string = "",
    content: string = "",
    timestamp: i64 = 0
  ) {
    this.messageId = messageId;
    this.content = content;
    this.timestamp = timestamp;
  }
}
