from _typeshed import Incomplete
from django.core.management.base import BaseCommand

logger: Incomplete
PANDAS_AVAILABLE: bool

class Command(BaseCommand):
    help: str
    def add_arguments(self, parser) -> None: ...
    def handle(self, *args, **options) -> None: ...
    def clean_csv(self, filepath: str, outpath: str) -> None: ...
    def _map_columns(self, df): ...
    def _clean_text_fields(self, df): ...
    def _process_boolean_fields(self, df): ...
    def _clean_date_fields(self, df): ...
    def _normalize_status_values(self, df): ...
    def _clean_project_phases(self, df): ...
    def _clean_environmental_aspects(self, df): ...
    def _clean_site_desktop_values(self, df): ...
    def _clean_email_addresses(self, df): ...
    def _format_obligation_numbers(self, df): ...
    def _apply_defaults_and_nulls(self, df): ...
