from ....mechanisms.models import EnvironmentalMechanism
from ....obligations.models import Obligation
from ....projects.models import Project
from _typeshed import Incomplete
from django.core.management.base import BaseCommand, CommandParser
from django.db.models import Model
from typing import Any, TypedDict

class DjangoModel(Model):
    id: int

class ProjectT(Project, DjangoModel): ...
class EnvironmentalMechanismT(EnvironmentalMechanism, DjangoModel): ...
class ObligationT(Obligation, DjangoModel): ...

logger: Incomplete

class ObligationData(TypedDict, total=False):
    obligation_number: str
    project: Project
    primary_environmental_mechanism: EnvironmentalMechanism | None
    procedure: str
    environmental_aspect: str
    obligation: str
    accountability: str
    responsibility: str
    project_phase: str
    action_due_date: Any | None
    close_out_date: Any | None
    status: str
    supporting_information: str
    general_comments: str
    compliance_comments: str
    non_conformance_comments: str
    evidence_notes: str
    recurring_obligation: bool
    recurring_frequency: str
    recurring_status: str
    recurring_forecasted_date: Any | None
    inspection: bool
    inspection_frequency: str
    site_or_desktop: str
    gap_analysis: bool
    notes_for_gap_analysis: str

class Command(BaseCommand):
    OBLIGATION_PREFIX_MAPPING: dict[str, str]
    def handle(self, *args: Any, **options: Any) -> None: ...
    def _get_or_create_project(self, project_name: str) -> Project | None: ...
    def _process_obligation_row(self, row: dict[str, Any], project: Project, options: dict[str, Any]) -> None: ...
    help: str
    MECHANISM_ID_MAPPING: dict[str, str]
    def add_arguments(self, parser: CommandParser) -> None: ...
    def clean_boolean(self, value: Any) -> bool: ...
    def normalize_obligation_number(self, obligation_number: str) -> str: ...
    def get_or_create_mechanism(self, mechanism_name: str | None, project: Project) -> tuple[EnvironmentalMechanism | None, bool]: ...
    def _retrieve_mechanism(self, mechanism_name: str, project: Project) -> EnvironmentalMechanism | None: ...
    def _create_mechanism(self, mechanism_name: str, project: Project) -> tuple[EnvironmentalMechanism | None, bool]: ...
    def map_environmental_aspect(self, aspect: str) -> str: ...
    def parse_date_safe(self, date_value: Any) -> Any | None: ...
    def generate_obligation_number(self) -> str: ...
    def process_row(self, row: dict[str, Any], project: Project) -> ObligationData: ...
    def _process_mechanism(self, row: dict[str, Any], project: Project) -> EnvironmentalMechanism | None: ...
    def _normalize_status(self, status: str) -> str: ...
    def _map_environmental_aspect(self, aspect: str | None) -> str: ...
    def _parse_date_safe(self, date_value: Any) -> Any | None: ...
    def _get_or_generate_obligation_number(self, obligation_number: str | None) -> str: ...
    def create_or_update_obligation(self, obligation_data: ObligationData, force_update: bool = False) -> tuple[Obligation | bool | None, str]: ...
