from _typeshed import Incomplete
from django.core.management.base import BaseCommand
from typing import Any

logger: Incomplete

class Command(BaseCommand):
    help: str
    def update_null_statuses(self): ...
    def validate_obligations(self): ...
    def update_mechanism_counts(self): ...
    def handle(self, *args: tuple[Any, ...], **options: dict[str, Any]) -> None: ...
