"""Copyright (C) 2024 Adrian Gallo <agallo@enveng-group.com.au>
This file is part of Greenova and is licensed under the AGPL-3.0.

Dashboard app models for Greenova.
"""

from typing import TYPE_CHECKING, Any, cast

from beartype import beartype
from django.contrib import admin
from django.db import models
from django.utils import timezone

if TYPE_CHECKING:
    from .models import ObligationSummary

# Protobuf integration imports (generated by protoc)
from protobuf import greenova_data_pb2  # type: ignore[import]

# --- Protobuf Integration ---
# Backend: Run `doit compile_proto_python` to generate *_pb2.py files from .proto schemas.
# Frontend: Use as-proto to generate TypeScript/AssemblyScript classes
# from the same .proto files.


@beartype
class ProjectSummary(models.Model):
    """Project summary for dashboard (matches protobuf ProjectSummary)."""

    class Meta:
        app_label = "dashboard"

    total_projects = models.IntegerField(default=0)
    active_projects = models.IntegerField(default=0)
    completed_projects = models.IntegerField(default=0)
    recent_projects = models.JSONField(default=list, blank=True)  # type: ignore

    def __str__(self) -> str:
        return f"ProjectSummary(total={
            self.total_projects}, active={
            self.active_projects})"

    def to_proto(self) -> "greenova_data_pb2.ProjectSummary":
        """Serialize to protobuf ProjectSummary."""
        proto = greenova_data_pb2.ProjectSummary()
        proto.total_projects = self.total_projects
        proto.active_projects = self.active_projects
        proto.completed_projects = self.completed_projects
        recent_projects: list[dict[str, Any]] = cast(
            "list[dict[str, Any]]",
            self.recent_projects if isinstance(self.recent_projects, list) else [],
        )
        for proj_dict in recent_projects:
            proj_msg = greenova_data_pb2.Project()
            for k, v in proj_dict.items():
                setattr(proj_msg, k, v)
            proto.recent_projects.append(proj_msg)
        return proto

    @classmethod
    def from_proto(cls, proto: "greenova_data_pb2.ProjectSummary") -> "ProjectSummary":
        """Deserialize from protobuf ProjectSummary."""
        recent_projects: list[dict[str, Any]] = []
        for p in proto.recent_projects:
            proj_dict: dict[str, Any] = {}
            for field, value in p.ListFields():
                proj_dict[field.name] = value
            recent_projects.append(proj_dict)
        return cls(
            total_projects=proto.total_projects,
            active_projects=proto.active_projects,
            completed_projects=proto.completed_projects,
            recent_projects=recent_projects,
        )


@beartype
class ObligationSummary(models.Model):
    """Obligation summary for dashboard (matches protobuf ObligationSummary)."""

    status = models.CharField(max_length=64)
    count = models.IntegerField(default=0)
    upcoming_obligations = models.JSONField(default=list, blank=True)  # type: ignore

    def __str__(self) -> str:
        return f"ObligationSummary(status={self.status}, count={self.count})"

    def to_proto(self) -> "greenova_data_pb2.ObligationSummary":
        """Serialize to protobuf ObligationSummary."""
        proto = greenova_data_pb2.ObligationSummary()
        proto.status = self.status
        proto.count = self.count
        upcoming_obligations: list[dict[str, Any]] = cast(
            "list[dict[str, Any]]",
            self.upcoming_obligations
            if isinstance(self.upcoming_obligations, list)
            else [],
        )
        for obl_dict in upcoming_obligations:
            obl_msg = greenova_data_pb2.Obligation()
            for k, v in obl_dict.items():
                setattr(obl_msg, k, v)
            proto.upcoming_obligations.append(obl_msg)
        return proto

    @classmethod
    def from_proto(
        cls, proto: "greenova_data_pb2.ObligationSummary"
    ) -> "ObligationSummary":
        """Deserialize from protobuf ObligationSummary."""
        upcoming_obligations: list[dict[str, Any]] = []
        for o in proto.upcoming_obligations:
            obl_dict: dict[str, Any] = {}
            for field, value in o.ListFields():
                obl_dict[field.name] = value
            upcoming_obligations.append(obl_dict)
        return cls(
            status=proto.status,
            count=proto.count,
            upcoming_obligations=upcoming_obligations,
        )


@beartype
class ComplianceMetrics(models.Model):
    """Compliance metrics for dashboard (matches protobuf ComplianceMetrics)."""

    overall_compliance_rate = models.FloatField(default=0.0)
    overdue_obligations = models.IntegerField(default=0)
    due_this_week = models.IntegerField(default=0)
    due_this_month = models.IntegerField(default=0)
    compliance_by_framework = models.JSONField(default=list, blank=True)  # type: ignore

    def __str__(self) -> str:
        return f"ComplianceMetrics(rate={self.overall_compliance_rate})"

    def to_proto(self) -> "greenova_data_pb2.ComplianceMetrics":
        """Serialize to protobuf ComplianceMetrics."""
        proto = greenova_data_pb2.ComplianceMetrics()
        proto.overall_compliance_rate = self.overall_compliance_rate
        proto.overdue_obligations = self.overdue_obligations
        proto.due_this_week = self.due_this_week
        proto.due_this_month = self.due_this_month
        compliance_by_framework: list[dict[str, Any]] = cast(
            "list[dict[str, Any]]",
            self.compliance_by_framework
            if isinstance(self.compliance_by_framework, list)
            else [],
        )
        for fw_dict in compliance_by_framework:
            fw_msg = greenova_data_pb2.ComplianceByFramework()
            for k, v in fw_dict.items():
                setattr(fw_msg, k, v)
            proto.compliance_by_framework.append(fw_msg)
        return proto

    @classmethod
    def from_proto(
        cls, proto: "greenova_data_pb2.ComplianceMetrics"
    ) -> "ComplianceMetrics":
        """Deserialize from protobuf ComplianceMetrics."""
        compliance_by_framework: list[dict[str, Any]] = []
        for f in proto.compliance_by_framework:
            fw_dict: dict[str, Any] = {}
            for field, value in f.ListFields():
                fw_dict[field.name] = value
            compliance_by_framework.append(fw_dict)
        return cls(
            overall_compliance_rate=proto.overall_compliance_rate,
            overdue_obligations=proto.overdue_obligations,
            due_this_week=proto.due_this_week,
            due_this_month=proto.due_this_month,
            compliance_by_framework=compliance_by_framework,
        )


@beartype
class DashboardData(models.Model):
    """DashboardData root message (matches protobuf DashboardData)."""

    project_summary = models.OneToOneField(ProjectSummary, on_delete=models.CASCADE)
    obligation_summaries = models.ManyToManyField("ObligationSummary")  # type: ignore
    compliance_metrics = models.OneToOneField(
        ComplianceMetrics, on_delete=models.CASCADE
    )
    last_updated = models.DateTimeField(default=timezone.now)

    def __str__(self) -> str:
        return f"DashboardData(last_updated={self.last_updated})"

    def to_proto(self) -> "greenova_data_pb2.DashboardData":
        """Serialize to protobuf DashboardData."""
        proto = greenova_data_pb2.DashboardData()
        proto.project_summary.CopyFrom(self.project_summary.to_proto())
        obligation_summaries_qs = (
            self.obligation_summaries.all()
            if hasattr(self.obligation_summaries, "all")
            else []
        )
        for obl in obligation_summaries_qs:
            if hasattr(obl, "to_proto"):
                proto.obligation_summaries.append(obl.to_proto())
        proto.compliance_metrics.CopyFrom(self.compliance_metrics.to_proto())
        proto.last_updated = int(self.last_updated.timestamp())
        return proto

    @classmethod
    def from_proto(cls, proto: "greenova_data_pb2.DashboardData") -> "DashboardData":
        """Deserialize from protobuf DashboardData. (Stub, not implemented)."""
        return cls(last_updated=timezone.now())


# Register models in admin
admin.site.register(ProjectSummary)
admin.site.register(ObligationSummary)
admin.site.register(ComplianceMetrics)
admin.site.register(DashboardData)
