from django.contrib.auth.decorators import login_required

@login_required
def responsibility_home(request): ...
@login_required
def assignment_list(request): ...
@login_required
def role_list(request): ...
