// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.24.4

import { Writer, Reader } from "as-proto/assembly";

export class ChartMetadata {
  static encode(message: ChartMetadata, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.dataSource);

    writer.uint32(16);
    writer.int64(message.generatedAt);

    writer.uint32(26);
    writer.string(message.generatedBy);

    const tags = message.tags;
    if (tags.length !== 0) {
      for (let i: i32 = 0; i < tags.length; ++i) {
        writer.uint32(34);
        writer.string(tags[i]);
      }
    }
  }

  static decode(reader: Reader, length: i32): ChartMetadata {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new ChartMetadata();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.dataSource = reader.string();
          break;

        case 2:
          message.generatedAt = reader.int64();
          break;

        case 3:
          message.generatedBy = reader.string();
          break;

        case 4:
          message.tags.push(reader.string());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  dataSource: string;
  generatedAt: i64;
  generatedBy: string;
  tags: Array<string>;

  constructor(
    dataSource: string = "",
    generatedAt: i64 = 0,
    generatedBy: string = "",
    tags: Array<string> = []
  ) {
    this.dataSource = dataSource;
    this.generatedAt = generatedAt;
    this.generatedBy = generatedBy;
    this.tags = tags;
  }
}
