// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.24.4

import { Writer, Reader } from "as-proto/assembly";
import { AxisConfig } from "./AxisConfig";

export class ChartConfig {
  static encode(message: ChartConfig, writer: Writer): void {
    writer.uint32(8);
    writer.int32(message.width);

    writer.uint32(16);
    writer.int32(message.height);

    writer.uint32(26);
    writer.string(message.colorScheme);

    writer.uint32(32);
    writer.bool(message.showLegend);

    writer.uint32(40);
    writer.bool(message.showGrid);

    const xAxis = message.xAxis;
    if (xAxis !== null) {
      writer.uint32(50);
      writer.fork();
      AxisConfig.encode(xAxis, writer);
      writer.ldelim();
    }

    const yAxis = message.yAxis;
    if (yAxis !== null) {
      writer.uint32(58);
      writer.fork();
      AxisConfig.encode(yAxis, writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): ChartConfig {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new ChartConfig();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.width = reader.int32();
          break;

        case 2:
          message.height = reader.int32();
          break;

        case 3:
          message.colorScheme = reader.string();
          break;

        case 4:
          message.showLegend = reader.bool();
          break;

        case 5:
          message.showGrid = reader.bool();
          break;

        case 6:
          message.xAxis = AxisConfig.decode(reader, reader.uint32());
          break;

        case 7:
          message.yAxis = AxisConfig.decode(reader, reader.uint32());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  width: i32;
  height: i32;
  colorScheme: string;
  showLegend: bool;
  showGrid: bool;
  xAxis: AxisConfig | null;
  yAxis: AxisConfig | null;

  constructor(
    width: i32 = 0,
    height: i32 = 0,
    colorScheme: string = "",
    showLegend: bool = false,
    showGrid: bool = false,
    xAxis: AxisConfig | null = null,
    yAxis: AxisConfig | null = null
  ) {
    this.width = width;
    this.height = height;
    this.colorScheme = colorScheme;
    this.showLegend = showLegend;
    this.showGrid = showGrid;
    this.xAxis = xAxis;
    this.yAxis = yAxis;
  }
}
