// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.24.4

import { Writer, Reader } from "as-proto/assembly";
import { ChartConfig } from "./ChartConfig";
import { DataSeries } from "./DataSeries";
import { ChartMetadata } from "./ChartMetadata";

export class ChartData {
  static encode(message: ChartData, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.chartId);

    writer.uint32(18);
    writer.string(message.chartType);

    writer.uint32(26);
    writer.string(message.title);

    const config = message.config;
    if (config !== null) {
      writer.uint32(34);
      writer.fork();
      ChartConfig.encode(config, writer);
      writer.ldelim();
    }

    const dataSeries = message.dataSeries;
    for (let i: i32 = 0; i < dataSeries.length; ++i) {
      writer.uint32(42);
      writer.fork();
      DataSeries.encode(dataSeries[i], writer);
      writer.ldelim();
    }

    const metadata = message.metadata;
    if (metadata !== null) {
      writer.uint32(50);
      writer.fork();
      ChartMetadata.encode(metadata, writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): ChartData {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new ChartData();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.chartId = reader.string();
          break;

        case 2:
          message.chartType = reader.string();
          break;

        case 3:
          message.title = reader.string();
          break;

        case 4:
          message.config = ChartConfig.decode(reader, reader.uint32());
          break;

        case 5:
          message.dataSeries.push(DataSeries.decode(reader, reader.uint32()));
          break;

        case 6:
          message.metadata = ChartMetadata.decode(reader, reader.uint32());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  chartId: string;
  chartType: string;
  title: string;
  config: ChartConfig | null;
  dataSeries: Array<DataSeries>;
  metadata: ChartMetadata | null;

  constructor(
    chartId: string = "",
    chartType: string = "",
    title: string = "",
    config: ChartConfig | null = null,
    dataSeries: Array<DataSeries> = [],
    metadata: ChartMetadata | null = null
  ) {
    this.chartId = chartId;
    this.chartType = chartType;
    this.title = title;
    this.config = config;
    this.dataSeries = dataSeries;
    this.metadata = metadata;
  }
}
