// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.24.4

export enum ComplianceStatus {
  COMPLIANT = 0,
  WARNING = 1,
  NON_COMPLIANT = 2,
  UNKNOWN = 3,
}
