// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.24.4

import { Writer, Reader } from "as-proto/assembly";
import { DataPoint } from "./DataPoint";

export class DataSeries {
  static encode(message: DataSeries, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.seriesName);

    const dataPoints = message.dataPoints;
    for (let i: i32 = 0; i < dataPoints.length; ++i) {
      writer.uint32(18);
      writer.fork();
      DataPoint.encode(dataPoints[i], writer);
      writer.ldelim();
    }

    writer.uint32(26);
    writer.string(message.color);

    writer.uint32(34);
    writer.string(message.lineStyle);
  }

  static decode(reader: Reader, length: i32): DataSeries {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new DataSeries();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.seriesName = reader.string();
          break;

        case 2:
          message.dataPoints.push(DataPoint.decode(reader, reader.uint32()));
          break;

        case 3:
          message.color = reader.string();
          break;

        case 4:
          message.lineStyle = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  seriesName: string;
  dataPoints: Array<DataPoint>;
  color: string;
  lineStyle: string;

  constructor(
    seriesName: string = "",
    dataPoints: Array<DataPoint> = [],
    color: string = "",
    lineStyle: string = ""
  ) {
    this.seriesName = seriesName;
    this.dataPoints = dataPoints;
    this.color = color;
    this.lineStyle = lineStyle;
  }
}
