// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.24.4

import { Writer, Reader } from "as-proto/assembly";

export class DataPoint {
  static encode(message: DataPoint, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.stringX);

    writer.uint32(17);
    writer.double(message.numericX);

    writer.uint32(24);
    writer.int64(message.timestampX);

    writer.uint32(33);
    writer.double(message.yValue);

    writer.uint32(42);
    writer.string(message.label);

    const metadata = message.metadata;
    if (metadata !== null) {
      const metadataKeys = metadata.keys();
      for (let i: i32 = 0; i < metadataKeys.length; ++i) {
        const metadataKey = metadataKeys[i];
        writer.uint32(50);
        writer.fork();
        writer.uint32(10);
        writer.string(metadataKey);
        writer.uint32(18);
        writer.string(metadata.get(metadataKey));
        writer.ldelim();
      }
    }
  }

  static decode(reader: Reader, length: i32): DataPoint {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new DataPoint();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.stringX = reader.string();
          break;

        case 2:
          message.numericX = reader.double();
          break;

        case 3:
          message.timestampX = reader.int64();
          break;

        case 4:
          message.yValue = reader.double();
          break;

        case 5:
          message.label = reader.string();
          break;

        case 6:
          let metadataKey: string = "";
          let metadataValue: string = "";
          let metadataHasKey: bool = false;
          let metadataHasValue: bool = false;
          for (
            const end: usize = reader.ptr + reader.uint32();
            reader.ptr < end;

          ) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
              case 1:
                metadataKey = reader.string();
                metadataHasKey = true;
                break;

              case 2:
                metadataValue = reader.string();
                metadataHasValue = true;
                break;

              default:
                reader.skipType(tag & 7);
                break;
            }
            if (message.metadata === null) {
              message.metadata = new Map<string, string>();
            }
            const metadata = message.metadata;
            if (metadata !== null && metadataHasKey && metadataHasValue) {
              metadata.set(metadataKey, metadataValue);
            }
          }
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  stringX: string;
  numericX: f64;
  timestampX: i64;
  yValue: f64;
  label: string;
  metadata: Map<string, string>;

  constructor(
    stringX: string = "",
    numericX: f64 = 0.0,
    timestampX: i64 = 0,
    yValue: f64 = 0.0,
    label: string = "",
    metadata: Map<string, string> = new Map()
  ) {
    this.stringX = stringX;
    this.numericX = numericX;
    this.timestampX = timestampX;
    this.yValue = yValue;
    this.label = label;
    this.metadata = metadata;
  }
}
