// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.24.4

import { Writer, Reader } from "as-proto/assembly";
import { MetricDataPoint } from "./MetricDataPoint";
import { MetricThresholds } from "./MetricThresholds";

export class EnvironmentalMetricsChart {
  static encode(message: EnvironmentalMetricsChart, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.metricType);

    writer.uint32(18);
    writer.string(message.measurementUnit);

    const metricPoints = message.metricPoints;
    for (let i: i32 = 0; i < metricPoints.length; ++i) {
      writer.uint32(26);
      writer.fork();
      MetricDataPoint.encode(metricPoints[i], writer);
      writer.ldelim();
    }

    const thresholds = message.thresholds;
    if (thresholds !== null) {
      writer.uint32(34);
      writer.fork();
      MetricThresholds.encode(thresholds, writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): EnvironmentalMetricsChart {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new EnvironmentalMetricsChart();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.metricType = reader.string();
          break;

        case 2:
          message.measurementUnit = reader.string();
          break;

        case 3:
          message.metricPoints.push(
            MetricDataPoint.decode(reader, reader.uint32())
          );
          break;

        case 4:
          message.thresholds = MetricThresholds.decode(reader, reader.uint32());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  metricType: string;
  measurementUnit: string;
  metricPoints: Array<MetricDataPoint>;
  thresholds: MetricThresholds | null;

  constructor(
    metricType: string = "",
    measurementUnit: string = "",
    metricPoints: Array<MetricDataPoint> = [],
    thresholds: MetricThresholds | null = null
  ) {
    this.metricType = metricType;
    this.measurementUnit = measurementUnit;
    this.metricPoints = metricPoints;
    this.thresholds = thresholds;
  }
}
