// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.24.4

import { Writer, Reader } from "as-proto/assembly";
import { ComplianceStatus } from "./ComplianceStatus";

export class MetricDataPoint {
  static encode(message: MetricDataPoint, writer: Writer): void {
    writer.uint32(8);
    writer.int64(message.timestamp);

    writer.uint32(17);
    writer.double(message.value);

    writer.uint32(26);
    writer.string(message.location);

    writer.uint32(34);
    writer.string(message.measurementMethod);

    writer.uint32(40);
    writer.int32(message.complianceStatus);
  }

  static decode(reader: Reader, length: i32): MetricDataPoint {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new MetricDataPoint();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.timestamp = reader.int64();
          break;

        case 2:
          message.value = reader.double();
          break;

        case 3:
          message.location = reader.string();
          break;

        case 4:
          message.measurementMethod = reader.string();
          break;

        case 5:
          message.complianceStatus = reader.int32();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  timestamp: i64;
  value: f64;
  location: string;
  measurementMethod: string;
  complianceStatus: ComplianceStatus;

  constructor(
    timestamp: i64 = 0,
    value: f64 = 0.0,
    location: string = "",
    measurementMethod: string = "",
    complianceStatus: ComplianceStatus = 0
  ) {
    this.timestamp = timestamp;
    this.value = value;
    this.location = location;
    this.measurementMethod = measurementMethod;
    this.complianceStatus = complianceStatus;
  }
}
