// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.24.4

import { Writer, Reader } from "as-proto/assembly";

export class MetricThresholds {
  static encode(message: MetricThresholds, writer: Writer): void {
    writer.uint32(9);
    writer.double(message.warningThreshold);

    writer.uint32(17);
    writer.double(message.criticalThreshold);

    writer.uint32(25);
    writer.double(message.targetValue);
  }

  static decode(reader: Reader, length: i32): MetricThresholds {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new MetricThresholds();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.warningThreshold = reader.double();
          break;

        case 2:
          message.criticalThreshold = reader.double();
          break;

        case 3:
          message.targetValue = reader.double();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  warningThreshold: f64;
  criticalThreshold: f64;
  targetValue: f64;

  constructor(
    warningThreshold: f64 = 0.0,
    criticalThreshold: f64 = 0.0,
    targetValue: f64 = 0.0
  ) {
    this.warningThreshold = warningThreshold;
    this.criticalThreshold = criticalThreshold;
    this.targetValue = targetValue;
  }
}
