from _typeshed import Incomplete

register: Incomplete

@register.filter
def full_name_or_username(user): ...
@register.filter
def profile_image_url(user): ...
@register.simple_tag
def user_role(user): ...
@register.filter
def auth_user_display(user): ...
@register.simple_tag
def auth_status_badge(user): ...
@register.filter
def has_verified_email(user): ...
def login_url_with_next(context): ...
