from _typeshed import Incomplete
from matplotlib.figure import Figure

logger: Incomplete

def generate_pie_chart(data: list[int], labels: list[str], colors: list[str], fig_width: int = 300, fig_height: int = 250) -> Figure: ...
def encode_figure_to_base64(fig: Figure) -> str: ...
def get_mechanism_chart(mechanism_id: int, fig_width: int = 300, fig_height: int = 250) -> tuple[Figure, str]: ...
def get_overall_chart(project_id: int, fig_width: int = 300, fig_height: int = 250) -> tuple[Figure, str]: ...
