# Dependency Review Action
# This workflow scans dependency manifest files in pull requests for known vulnerabilities.
# For more information, see:
# https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-dependency-review#dependency-review-enforcement

name: 'Dependency review'

on:
  pull_request:
    branches: ['main'] # Run on pull requests targeting the main branch

permissions:
  contents: read # Required to read repository contents
  pull-requests: write # Required to add comments to pull requests

jobs:
  dependency-review:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4 # Check out the repository code

      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v4 # Run the dependency review action
        with:
          comment-summary-in-pr: always # Always add a summary comment to the pull request
          # Uncomment the following options to customize the workflow:
          # fail-on-severity: moderate # Fail the workflow for vulnerabilities of moderate severity or higher
          # deny-licenses: GPL-1.0-or-later, LGPL-2.0-or-later # Deny specific licenses
          # retry-on-snapshot-warnings: true # Retry if snapshot warnings occur
